# Generated by Django 5.2.9 on 2025-12-28 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.CreateModel(
            name='ProductCategoryRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_relations', to='core.productcategory', verbose_name='دسته\u200cبندی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_relations', to='core.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'رابطه محصول-دسته',
                'verbose_name_plural': 'روابط محصول-دسته',
                'unique_together': {('product', 'category')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', through='core.ProductCategoryRelation', to='core.productcategory', verbose_name='دسته\u200cبندی\u200cها'),
        ),
    ]
