# Generated by Django 5.2.9 on 2025-12-31 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_productquantity_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام شرکت'),
        ),
        migrations.AddField(
            model_name='order',
            name='full_address',
            field=models.TextField(blank=True, help_text='شامل: استان، شهر، کدپستی و آدرس دقیق', null=True, verbose_name='آدرس کامل پستی'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(blank=True, help_text='نام و نام خانوادگی در لحظه ثبت سفارش', max_length=255, null=True, verbose_name='نام گیرنده'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس گیرنده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, help_text='در صورت نال بودن، سفارش به عنوان مهمان ثبت شده است.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='مشتری'),
        ),
    ]
