# Generated by Django 5.2.11 on 2026-02-14 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_address_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات / دلیل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='کاربری که وضعیت را تغییر داده (طراح، انباردار و...)', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='تغییر دهنده')),
                ('from_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_from', to='core.orderstatus', verbose_name='از وضعیت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_logs', to='core.order', verbose_name='سفارش')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs_to', to='core.orderstatus', verbose_name='به وضعیت')),
            ],
            options={
                'verbose_name': 'تاریخچه وضعیت',
                'verbose_name_plural': 'تاریخچه\u200cهای وضعیت',
                'db_table': 'admin_order_state_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
