# Generated by Django 5.2.11 on 2026-02-20 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_invoice_order_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'ordering': ('sort_order',), 'verbose_name': 'وضعیت سفارش', 'verbose_name_plural': 'وضعیت\u200cهای سفارش'},
        ),
        migrations.AddField(
            model_name='productquantity',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='مثال: قیمت پایه ۱۰۰۰ عدد کارت ویزیت بدون هیچ ویژگی اضافه\u200cای.', max_digits=12, verbose_name='قیمت پایه در این تیراژ'),
        ),
        migrations.AlterField(
            model_name='productoptionvalue',
            name='has_pricing',
            field=models.BooleanField(default=True, verbose_name='آیا روی قیمت تاثیر دارد؟'),
        ),
        migrations.AlterField(
            model_name='productoptionvalue',
            name='price_impact',
            field=models.DecimalField(decimal_places=0, default=0, help_text="اگر محصول 'تعدادی' است، این مبلغ با تعداد جمع/ضرب می\u200cشود. اگر تیراژی است و در ماتریس قیمتی ندارد، از این عدد استفاده می\u200cشود.", max_digits=14, verbose_name='قیمت پیش\u200cفرض (تعدادی)'),
        ),
        migrations.AlterUniqueTogether(
            name='productquantity',
            unique_together={('product', 'quantity')},
        ),
        migrations.CreateModel(
            name='OptionValueQuantityPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, default=0, help_text='این مبلغ در این تیراژ، جایگزین price_impact پیش\u200cفرض خواهد شد.', max_digits=12, verbose_name='مبلغ جایگزین (Override)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_prices', to='core.productoptionvalue', verbose_name='مقدار ویژگی')),
                ('product_quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_prices', to='core.productquantity', verbose_name='تیراژ محصول')),
            ],
            options={
                'verbose_name': 'قیمت ویژگی در تیراژ',
                'verbose_name_plural': 'ماتریس قیمت ویژگی\u200cها',
                'unique_together': {('option_value', 'product_quantity')},
            },
        ),
    ]
