# Generated by Django 5.2.11 on 2026-02-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='سررسید'),
        ),
    ]
