# Generated by Django 5.2.8 on 2025-11-30 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0014_productcomment_productrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customernotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'اعلان', 'verbose_name_plural': 'اعلان ها'},
        ),
        migrations.AddField(
            model_name='customernotification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده'),
        ),
        migrations.AlterField(
            model_name='customernotification',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع مدل'),
        ),
        migrations.AlterField(
            model_name='customernotification',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='customernotification',
            name='name',
            field=models.CharField(max_length=150, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='customernotification',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='آی\u200cدی شیء'),
        ),
        migrations.AlterField(
            model_name='customernotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='گیرنده'),
        ),
        migrations.AlterField(
            model_name='customernotification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='فرستنده'),
        ),
        migrations.AddIndex(
            model_name='customernotification',
            index=models.Index(fields=['recipient', 'is_read'], name='core_custom_recipie_bdc6dc_idx'),
        ),
    ]
