# Generated by Django 5.2.8 on 2025-11-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_customernotification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='banner_box',
            field=models.ImageField(blank=True, help_text='تصویر برای نمایش در لیست دسته\u200cبندی\u200cها (مثلاً 400x400)', null=True, upload_to='categories/boxes/', verbose_name='بنر مربعی/باکس'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='banner_wide',
            field=models.ImageField(blank=True, help_text='تصویر عریض برای هدر صفحه (مثلاً 1920x400)', null=True, upload_to='categories/banners/', verbose_name='بنر عریض'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات برای نمایش در بالای صفحه دسته بندی و سئو', null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
    ]
