# Generated by Django 5.2.11 on 2026-02-21 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_product_show_price_alter_order_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoption',
            name='option',
        ),
        migrations.RemoveField(
            model_name='optionvalue',
            name='option',
        ),
        migrations.RemoveField(
            model_name='productoptionvalue',
            name='global_source',
        ),
        migrations.AlterUniqueTogether(
            name='optionvaluequantityprice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='optionvaluequantityprice',
            name='option_value',
        ),
        migrations.RemoveField(
            model_name='optionvaluequantityprice',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productoptionvalue',
            name='product_option',
        ),
        migrations.AlterUniqueTogether(
            name='productoptioncondition',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productoptioncondition',
            name='required_value',
        ),
        migrations.RemoveField(
            model_name='productoptioncondition',
            name='target_value',
        ),
        migrations.RemoveField(
            model_name='productpricingconfig',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='productquantity',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productquantity',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productquantity',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='productquantity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productsize',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='size',
            name='user',
        ),
        migrations.CreateModel(
            name='ProductField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان فیلد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('field_type', models.CharField(choices=[('text', 'متن کوتاه'), ('textarea', 'متن چندخطی'), ('number', 'عدد'), ('single_select', 'تک انتخابی (Radio)'), ('multi_select', 'چند انتخابی (Checkbox)'), ('dropdown', 'کشویی (Select)')], default='dropdown', max_length=20, verbose_name='نوع فیلد')),
                ('numeric_value', models.DecimalField(decimal_places=2, default=0.0, help_text='اگر خود فیلد به تنهایی دارای ارزش عددی/قیمتی در فرمول است (مستقل از زیرمجموعه\u200cها)', max_digits=14, verbose_name='مقدار عددی پایه (برای فرمول)')),
                ('is_required', models.BooleanField(default=False, verbose_name='اجباری بودن')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن')),
                ('is_quantity_field', models.BooleanField(default=False, verbose_name='آیا این فیلد همان تیراژ است؟')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='core.product', verbose_name='محصول')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductFieldChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان مقدار')),
                ('numeric_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='مقدار عددی (برای فرمول)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.productfield')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductFieldCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('equals', 'برابر با'), ('not_equals', 'به غیر از'), ('is_empty', 'خالی باشد'), ('is_not_empty', 'خالی نباشد')], max_length=20, verbose_name='عملگر')),
                ('trigger_value_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='مقدار شرط (برای متن/عدد)')),
                ('action', models.CharField(choices=[('show', 'آشکار شود'), ('hide', 'پنهان شود'), ('enable', 'فعال شود'), ('disable', 'غیرفعال شود')], max_length=20, verbose_name='عملیات')),
                ('target_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_conditions', to='core.productfield', verbose_name='فیلد هدف')),
                ('trigger_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productfieldchoice', verbose_name='مقدار شرط (برای لیست\u200cها)')),
                ('trigger_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggering_conditions', to='core.productfield', verbose_name='فیلد شرط')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان فرمول')),
                ('condition_expression', models.CharField(blank=True, help_text='مثال: field_15 > 1000', max_length=255, null=True, verbose_name='شرط اجرای فرمول')),
                ('calculation_expression', models.TextField(help_text='فرمول ریاضی با استفاده از ID فیلدها. مثال: (field_12 * field_15) + 500', verbose_name='عبارت محاسباتی')),
                ('currency', models.CharField(default='IQD', editable=False, max_length=10, verbose_name='واحد پولی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='core.product')),
            ],
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='OptionValue',
        ),
        migrations.DeleteModel(
            name='OptionValueQuantityPrice',
        ),
        migrations.DeleteModel(
            name='ProductOption',
        ),
        migrations.DeleteModel(
            name='ProductOptionCondition',
        ),
        migrations.DeleteModel(
            name='ProductOptionValue',
        ),
        migrations.DeleteModel(
            name='ProductPricingConfig',
        ),
        migrations.DeleteModel(
            name='ProductQuantity',
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
        migrations.DeleteModel(
            name='Quantity',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
