# Generated by Django 5.2.8 on 2025-12-01 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_productcategory_banner_box_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productmaterial',
            unique_together={('product', 'material')},
        ),
        migrations.AddField(
            model_name='material',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='material',
            name='price_per_sqm',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='قیمت بر متر مربع'),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات فنی'),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='extra_price_per_unit',
            field=models.DecimalField(decimal_places=0, default=0, help_text='مبلغی که فارغ از متراژ، به ازای استفاده از این جنس اضافه می\u200cشود.', max_digits=12, verbose_name='هزینه اضافه ثابت'),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='is_default',
            field=models.BooleanField(default=False, help_text='آیا این جنس به صورت پیش\u200cفرض انتخاب شده باشد؟', verbose_name='پیش\u200cفرض'),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='processing_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='درصدی که به قیمت خام متریال اضافه می\u200cشود (مثلاً 10 درصد بابت برش سخت)', max_digits=5, verbose_name='درصد هزینه پردازش/سختی کار'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='اجباری'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='pricing_type',
            field=models.CharField(choices=[('fixed', 'مبلغ ثابت (IQD)'), ('per_unit', 'به ازای هر عدد (IQD)'), ('per_sqm', 'به ازای متر مربع (IQD)'), ('percentage', 'درصدی از کل قیمت (%)')], default='fixed', max_length=20, verbose_name='نحوه محاسبه'),
        ),
        migrations.CreateModel(
            name='ProductPricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_custom_quantity', models.BooleanField(default=False, verbose_name='امکان تیراژ دلخواه')),
                ('min_quantity', models.PositiveIntegerField(default=100, verbose_name='حداقل تیراژ')),
                ('max_quantity', models.PositiveIntegerField(default=10000, verbose_name='حداکثر تیراژ')),
                ('accepts_custom_dimensions', models.BooleanField(default=False, verbose_name='پذیرش ابعاد دلخواه')),
                ('min_width', models.FloatField(default=0, verbose_name='حداقل عرض (cm)')),
                ('max_width', models.FloatField(default=0, verbose_name='حداکثر عرض (cm)')),
                ('base_setup_price', models.DecimalField(decimal_places=0, default=0, help_text='هزینه زینک، قالب یا تنظیم دستگاه که ربطی به تیراژ ندارد.', max_digits=12, verbose_name='هزینه ثابت اولیه (Setup)')),
                ('design_service_available', models.BooleanField(default=True, verbose_name='ارائه خدمات طراحی')),
                ('design_fee', models.DecimalField(decimal_places=0, default=0, help_text='اگر کاربر فایل نداشت، این مبلغ اضافه می\u200cشود.', max_digits=12, verbose_name='هزینه طراحی پایه')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_config', to='core.product', verbose_name='محصول مرتبط')),
            ],
            options={
                'verbose_name': 'تنظیمات قیمت و سفارش',
                'verbose_name_plural': 'تنظیمات قیمت و سفارش',
            },
        ),
        migrations.RemoveField(
            model_name='productmaterial',
            name='price_impact',
        ),
    ]
