# Generated by Django 5.2.8 on 2025-12-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_productmaterial_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='accepts_custom_dimensions',
        ),
    ]
