# Generated by Django 5.2.11 on 2026-02-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfieldchoice',
            name='is_default',
            field=models.BooleanField(default=False, help_text='آیا این گزینه در فرانت\u200cاند به صورت پیش\u200cفرض انتخاب شده باشد؟', verbose_name='گزینه پیش\u200cفرض'),
        ),
    ]
