# Generated by Django 5.2.8 on 2025-12-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_product_accepts_custom_dimensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('subject', models.CharField(max_length=255, verbose_name='موضوع پیام')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده توسط ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پیام تماس با ما',
                'verbose_name_plural': 'پیام\u200cهای تماس با ما',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionalModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان مودال')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='banners/modals/', verbose_name='تصویر مودال')),
                ('cta_text', models.CharField(max_length=100, verbose_name='متن دکمه (CTA)')),
                ('cta_url', models.URLField(verbose_name='لینک دکمه')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'مودال تبلیغاتی',
                'verbose_name_plural': 'مودال\u200cهای تبلیغاتی',
            },
        ),
    ]
