# Generated by Django 5.2.8 on 2025-12-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_contactus_promotionalmodal'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='آیا نقش برای مشتری است؟'),
        ),
    ]
