# Generated by Django 5.2.8 on 2025-12-02 14:33

import django.core.validators
import django.db.models.deletion
import mptt.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_role_is_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'بانک ویژگی', 'verbose_name_plural': 'بانک ویژگی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='optionvalue',
            options={'verbose_name': 'الگوی مقدار ویژگی', 'verbose_name_plural': 'الگوهای مقادیر ویژگی'},
        ),
        migrations.AlterModelOptions(
            name='productoption',
            options={'ordering': ['order'], 'verbose_name': 'پیکربندی ویژگی محصول', 'verbose_name_plural': 'پیکربندی ویژگی\u200cهای محصولات'},
        ),
        migrations.RemoveField(
            model_name='option',
            name='code',
        ),
        migrations.RemoveField(
            model_name='option',
            name='user',
        ),
        migrations.RemoveField(
            model_name='optionvalue',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='productoption',
            unique_together={('product', 'option')},
        ),
        migrations.AddField(
            model_name='option',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات راهنما'),
        ),
        migrations.AddField(
            model_name='option',
            name='input_type',
            field=models.CharField(choices=[('text', 'ورودی متنی (Text)'), ('textarea', 'ورودی متن بلند (Textarea)'), ('number', 'ورودی عددی (Number)'), ('select', 'لیست کشویی (Select)'), ('radio', 'رادیو باتن (Radio)'), ('checkbox', 'چک\u200cباکس چندتایی (Checkbox)'), ('boolean', 'سوییچ / تیک (Boolean)')], default='select', max_length=20, verbose_name='نوع ورودی'),
        ),
        migrations.AddField(
            model_name='option',
            name='label',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان نمایشی'),
        ),
        migrations.AddField(
            model_name='optionvalue',
            name='label',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان مقدار'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='base_price',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='هزینه\u200cای که صرفاً بابت وجود این ویژگی اضافه می\u200cشود (مستقل از انتخاب کاربر).', max_digits=14, verbose_name='هزینه سربار (Setup Cost)'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='has_pricing',
            field=models.BooleanField(default=True, help_text='سطح ۱ کنترل: اگر خاموش باشد، کل این ویژگی غیرمالی می\u200cشود.', verbose_name='محاسبه قیمت فعال است؟'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='pricing_strategy',
            field=models.CharField(choices=[('fixed', 'مبلغ ثابت (Fixed Amount)'), ('percentage', 'درصدی از قیمت پایه (Percentage)'), ('per_sqm', 'براساس متر مربع (Area * Rate)'), ('per_perimeter', 'براساس متر محیط (Perimeter * Rate)'), ('per_unit', 'براساس عدد ورودی کاربر (Input * Rate)')], default='fixed', help_text='تعیین فرمول محاسبه (ثابت، متری، درصدی و...)', max_length=20, verbose_name='استراتژی محاسبه قیمت'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='material',
            name='price_per_sqm',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='قیمت بر متر مربع'),
        ),
        migrations.AlterField(
            model_name='material',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='option',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(help_text='شناسه یکتا برای کدنویسی (مثال: paper_type)', max_length=150, unique=True, verbose_name='نام سیستمی'),
        ),
        migrations.AlterField(
            model_name='option',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='global_values', to='core.option'),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='value',
            field=models.CharField(max_length=150, verbose_name='کد سیستمی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='attachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_attachment_file', to='core.attachment'),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_attachment_product', to='core.product'),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_attachment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.productcategory'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='core.productcomment', verbose_name='پاسخ به'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='core.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_comments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='productfileuploadrequirement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_upload_requirements', to='core.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_image', to='core.product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_product_image', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_product', to='core.material'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_material', to='core.product'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_material', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='اجباری؟'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_configs', to='core.option'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='core.product'),
        ),
        migrations.AlterField(
            model_name='productpricingconfig',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pricing_config', to='core.product', verbose_name='محصول مرتبط'),
        ),
        migrations.AlterField(
            model_name='productquantity',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_quantity', to='core.product'),
        ),
        migrations.AlterField(
            model_name='productquantity',
            name='quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quantity_product', to='core.quantity'),
        ),
        migrations.AlterField(
            model_name='productquantity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_quantity_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='core.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_ratings', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_size', to='core.product'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='size_product', to='core.size'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_size', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quantity_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='value',
            field=models.PositiveIntegerField(unique=True, verbose_name='تیراژ'),
        ),
        migrations.AlterField(
            model_name='size',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='size_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=150, verbose_name='عنوان نمایشی')),
                ('value', models.CharField(blank=True, max_length=150, verbose_name='مقدار سیستمی')),
                ('has_pricing', models.BooleanField(default=True, help_text='سطح ۲ کنترل: اگر خاموش باشد، قیمت این گزینه صفر لحاظ می\u200cشود.', verbose_name='شامل هزینه می\u200cشود؟')),
                ('price_impact', models.DecimalField(decimal_places=0, default=Decimal('0'), help_text='اگر استراتژی ثابت است: کل مبلغ. اگر متری/تعدادی است: نرخ واحد.', max_digits=14, verbose_name='مبلغ / نرخ واحد')),
                ('quantity_step', models.PositiveIntegerField(default=1, help_text='قیمت بالا به ازای چه تعدادی است؟ (مثلا: ۱۰۰۰ تومان به ازای هر ۱۰ عدد).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='گام شمارش (تعداد مبنا)')),
                ('is_step_ceiling', models.BooleanField(default=False, help_text='اگر فعال باشد، ۱۵ عدد را ۲ بسته ۱۰ تایی حساب می\u200cکند (گرد به بالا).', verbose_name='محاسبه بسته\u200cای (Ceiling)؟')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('global_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.optionvalue', verbose_name='کپی از الگوی گلوبال')),
                ('product_option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choices', to='core.productoption')),
            ],
            options={
                'verbose_name': 'گزینه انتخابی نهایی',
                'verbose_name_plural': 'گزینه\u200cهای انتخابی نهایی',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='option_value',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='price_impact',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='pricing_type',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='user',
        ),
    ]
