# Generated by Django 5.2.8 on 2025-12-02 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_option_options_alter_optionvalue_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemdesignfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='orderitemdesignfile',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='orderitemdesignfile',
            name='user',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='items',
            field=models.JSONField(blank=True, null=True, verbose_name='جزئیات سفارش'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='قیمت'),
        ),
        migrations.CreateModel(
            name='OrderItemFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/designs/%Y/%m/%d/', verbose_name='فایل نهایی')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.orderitem', verbose_name='آیتم سفارش')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.productfileuploadrequirement', verbose_name='نوع فایل')),
            ],
            options={
                'verbose_name': 'فایل آیتم سفارش',
                'verbose_name_plural': 'فایل\u200cهای آیتم سفارش',
            },
        ),
        migrations.DeleteModel(
            name='DesignFile',
        ),
        migrations.DeleteModel(
            name='OrderItemDesignFile',
        ),
    ]
