# Generated by Django 5.2.8 on 2025-12-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_orderitemdesignfile_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploadspec',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='fileuploadspec',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ به روزرسانی'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_price',
            field=models.BooleanField(default=True, verbose_name='دارای قیمت'),
        ),
        migrations.AddField(
            model_name='productfileuploadrequirement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AddField(
            model_name='productfileuploadrequirement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ به روزرسانی'),
        ),
    ]
