# Generated by Django 5.2.14 on 2026-06-03 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_address_postal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='عنوان هزینه')),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('order', models.ForeignKey(blank=True, help_text='در صورت خالی بودن، هزینه عمومی محسوب می\u200cشود', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='core.order', verbose_name='سفارش مرتبط')),
            ],
            options={
                'verbose_name': 'هزینه',
                'verbose_name_plural': 'هزینه\u200cها',
                'db_table': 'core_expenses',
                'ordering': ['-created_at'],
            },
        ),
    ]
