# Generated by Django 5.2.9 on 2025-12-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_fileuploadspec_created_at_fileuploadspec_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدرها',
                'ordering': ['-created_at'],
            },
        ),
    ]
