# Generated by Django 5.2.14 on 2026-06-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_per_unit',
            field=models.PositiveIntegerField(default=0, help_text='قیمت بالا به ازای چه تعدادی است؟ (مثلا: ۱۰۰۰ تومان به ازای هر ۱۰ عدد).', verbose_name='گام شمارش (تعداد مبنا)'),
        ),
    ]
