# Generated by Django 5.2.9 on 2025-12-07 17:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_sliderindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان روش')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_price_dynamic', models.BooleanField(default=False, verbose_name='قیمت شناور؟')),
                ('base_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='هزینه پایه')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'روش ارسال',
                'verbose_name_plural': 'روش\u200cهای ارسال',
            },
        ),
        migrations.CreateModel(
            name='InvoiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان وضعیت')),
                ('internal_code', models.SlugField(help_text='برای استفاده در لاجیک کد (مثلا: PAID_FULL)', unique=True, verbose_name='کد سیستمی')),
                ('is_considered_paid', models.BooleanField(default=False, verbose_name='به معنی پرداخت شده است؟')),
                ('allows_editing', models.BooleanField(default=True, verbose_name='اجازه ویرایش فاکتور دارد؟')),
                ('color', models.CharField(default='secondary', help_text='primary, success, danger, ...', max_length=20, verbose_name='رنگ نمایش')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'وضعیت فاکتور',
                'verbose_name_plural': 'وضعیت\u200cهای فاکتور',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='OrderCostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان هزینه')),
                ('code', models.SlugField(help_text='برای استفاده در محاسبات (مثلا: SHIPPING_FEE)', unique=True, verbose_name='کد سیستمی')),
                ('category', models.CharField(choices=[('production', 'تولید و چاپ'), ('logistics', 'انبار و ارسال'), ('design', 'طراحی'), ('general', 'عمومی/سربار')], max_length=20, verbose_name='دسته بندی')),
                ('is_deduction', models.BooleanField(default=False, verbose_name='کسورات؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نوع هزینه',
                'verbose_name_plural': 'انواع هزینه',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'آیتم سفارش', 'verbose_name_plural': 'اقلام سفارش'},
        ),
        migrations.AlterModelOptions(
            name='orderitemfile',
            options={'ordering': ['-version'], 'verbose_name': 'فایل طراحی', 'verbose_name_plural': 'فایل\u200cهای طراحی'},
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'verbose_name': 'وضعیت سفارش', 'verbose_name_plural': 'وضعیت\u200cهای سفارش'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
        migrations.AddField(
            model_name='order',
            name='base_products_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ پایه اقلام'),
        ),
        migrations.AddField(
            model_name='order',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.orderstatus', verbose_name='وضعیت فعلی'),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کلی مشتری'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='کد پیگیری'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='admin_note',
            field=models.TextField(blank=True, help_text='مخصوص اپراتور چاپ', verbose_name='یادداشت تولید'),
        ),
        migrations.AddField(
            model_name='orderitemfile',
            name='admin_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='دلیل رد شدن / توضیحات QC'),
        ),
        migrations.AddField(
            model_name='orderitemfile',
            name='is_latest',
            field=models.BooleanField(default=True, verbose_name='آخرین نسخه است؟'),
        ),
        migrations.AddField(
            model_name='orderitemfile',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده (نیازمند اصلاح)')], default='pending', max_length=20, verbose_name='وضعیت فایل'),
        ),
        migrations.AddField(
            model_name='orderitemfile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitemfile',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='نسخه فایل'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='group',
            field=models.CharField(choices=[('financial', 'مالی'), ('design', 'طراحی'), ('qc', 'کنترل کیفی'), ('production', 'تولید و چاپ'), ('logistics', 'ارسال و تحویل'), ('other', 'سایر')], default='other', max_length=20, verbose_name='گروه وضعیت'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='internal_code',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='کد سیستمی'),
        ),
        migrations.AddField(
            model_name='role',
            name='slug',
            field=models.SlugField(default=uuid.UUID('65ecf687-d717-4540-a06e-04108c9a2515'), unique=True, verbose_name='کد سیستمی'),
        ),
        migrations.AddField(
            model_name='role',
            name='type',
            field=models.CharField(choices=[('admin', 'ادمین'), ('normal', 'کاربر عادی')], default='normal', max_length=150, verbose_name='نوع کاربر'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ کل سفارش'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='name',
            field=models.CharField(max_length=150, verbose_name='عنوان نمایشی'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('proforma', 'پیش\u200cفاکتور'), ('final', 'فاکتور رسمی')], default='proforma', max_length=20, verbose_name='نوع سند')),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='شماره فاکتور')),
                ('items_amount', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='جمع اقلام')),
                ('services_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='جمع خدمات و هزینه\u200cها')),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مالیات')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='تخفیف')),
                ('final_amount', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ کل فاکتور')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ دریافتی تایید شده')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='سررسید')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ قطعی شدن فاکتور')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات فاکتور')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='core.order', verbose_name='سفارش مرتبط')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='core.invoicestatus', verbose_name='وضعیت جاری')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceStateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, verbose_name='توضیحات (علت تغییر)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='تغییر دهنده')),
                ('from_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_from', to='core.invoicestatus')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_to', to='core.invoicestatus')),
            ],
            options={
                'verbose_name': 'لاگ وضعیت فاکتور',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrderCostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ (ریال)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='شرح هزینه')),
                ('is_approved_by_finance', models.BooleanField(default=False, verbose_name='تایید مالی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='core.order', verbose_name='سفارش')),
                ('order_item', models.ForeignKey(blank=True, help_text='اگر خالی باشد، هزینه عمومی سفارش محسوب می\u200cشود (مثل هزینه ارسال)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specific_costs', to='core.orderitem', verbose_name='آیتم مرتبط')),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ordercosttype', verbose_name='نوع هزینه')),
            ],
            options={
                'verbose_name': 'قلم هزینه',
                'verbose_name_plural': 'اقلام هزینه',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='شماره فاکتور')),
                ('items_total', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='جمع بهای کالاها')),
                ('services_total', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='جمع خدمات و هزینه\u200cها')),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مالیات (۹٪)')),
                ('profit_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='سود / کارمزد')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='تخفیف کل')),
                ('final_payable_amount', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ قابل پرداخت')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ پرداخت شده')),
                ('status', models.CharField(choices=[('pending', 'صادر شده - پرداخت نشده'), ('partially_paid', 'پرداخت ناقص (پیش\u200cپرداخت)'), ('paid', 'تسویه شده'), ('cancelled', 'باطل شده')], default='pending', max_length=20, verbose_name='وضعیت فاکتور')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ صدور')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='مهلت پرداخت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_order', to='core.order', verbose_name='سفارش مرتبط')),
            ],
            options={
                'verbose_name': 'فاکتور فروش',
                'verbose_name_plural': 'فاکتورهای فروش',
            },
        ),
        migrations.CreateModel(
            name='OrderShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری پستی')),
                ('driver_info', models.TextField(blank=True, help_text='نام و شماره تماس پیک', verbose_name='اطلاعات راننده/پیک')),
                ('shipping_cost_real', models.DecimalField(decimal_places=0, default=0, help_text='هزینه\u200cای که ما به پست پرداختیم', max_digits=15, verbose_name='هزینه واقعی ارسال')),
                ('status', models.CharField(choices=[('processing', 'در حال پردازش انبار'), ('ready_to_ship', 'آماده ارسال'), ('dispatched', 'تحویل به متصدی'), ('delivered', 'تحویل مشتری شد'), ('returned', 'مرجوع شد')], default='processing', max_length=20, verbose_name='وضعیت مرسوله')),
                ('expected_delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='زمان احتمالی تحویل')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج از انبار')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل به مشتری')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.deliverymethod', verbose_name='روش ارسال')),
                ('destination_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.address', verbose_name='آدرس مقصد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='core.order', verbose_name='سفارش مربوطه')),
            ],
            options={
                'verbose_name': 'مرسوله پستی',
                'verbose_name_plural': 'مرسولات پستی',
            },
        ),
        migrations.CreateModel(
            name='OrderStateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='زمان تغییر')),
                ('duration_in_previous_status', models.DurationField(blank=True, null=True, verbose_name='مدت توقف در مرحله قبل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات / دلیل تغییر')),
                ('from_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_from_status', to='core.orderstatus', verbose_name='از وضعیت')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_logs', to='core.order', verbose_name='سفارش مرتبط')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_to_status', to='core.orderstatus', verbose_name='به وضعیت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تغییر دهنده')),
            ],
            options={
                'verbose_name': 'تاریخچه تغییر وضعیت',
                'verbose_name_plural': 'تاریخچه تغییرات وضعیت',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrderTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ تراکنش')),
                ('transaction_type', models.CharField(choices=[('deposit', 'پیش پرداخت'), ('settlement', 'تسویه حساب'), ('refund', 'استرداد وجه')], max_length=20, verbose_name='نوع تراکنش')),
                ('gateway_name', models.CharField(blank=True, max_length=50, verbose_name='درگاه پرداخت')),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='کد مرجع بانکی')),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری')),
                ('status', models.CharField(choices=[('pending', 'در حال پردازش'), ('success', 'موفق'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پرداخت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.orderinvoice', verbose_name='فاکتور')),
            ],
            options={
                'verbose_name': 'تراکنش مالی سفارش',
                'verbose_name_plural': 'تراکنش\u200cهای مالی سفارش',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ واریزی')),
                ('method', models.CharField(choices=[('card_to_card', 'کارت به کارت'), ('bank_transfer', 'حواله بانکی (پایا/ساتنا)'), ('cash', 'وجه نقد (حضوری)'), ('cheque', 'چک'), ('pos', 'دستگاه کارتخوان (حضوری)')], max_length=20, verbose_name='روش پرداخت')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='financial/receipts/%Y/%m/', verbose_name='تصویر فیش/رسید')),
                ('tracking_code', models.CharField(help_text='شماره پیگیری فیش یا حواله', max_length=100, verbose_name='کد پیگیری/ارجاع')),
                ('payment_date', models.DateTimeField(help_text='زمانی که پول واریز شده (طبق فیش)', verbose_name='زمان واریز')),
                ('dest_account', models.CharField(blank=True, help_text='مثلا: بانک ملت - جاری', max_length=100, verbose_name='واریز به حساب')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید مالی'), ('confirmed', 'تایید شده'), ('rejected', 'رد شده / مغایرت')], default='pending', max_length=20, verbose_name='وضعیت سند')),
                ('rejection_reason', models.TextField(blank=True, help_text='اگر فیش جعلی است یا مبلغ نمی\u200cخواند', verbose_name='دلیل رد شدن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت در سیستم')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_transactions', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.invoice', verbose_name='فاکتور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'تراکنش / فیش',
                'verbose_name_plural': 'تراکنش\u200cها و فیش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه لیبل')),
                ('box_number', models.PositiveIntegerField(default=1, verbose_name='شماره بسته')),
                ('weight_grams', models.PositiveIntegerField(default=0, verbose_name='وزن (گرم)')),
                ('width_cm', models.PositiveIntegerField(default=0, verbose_name='عرض (cm)')),
                ('length_cm', models.PositiveIntegerField(default=0, verbose_name='طول (cm)')),
                ('height_cm', models.PositiveIntegerField(default=0, verbose_name='ارتفاع (cm)')),
                ('content_summary', models.TextField(blank=True, help_text='مثلا: ۱۰۰۰ عدد کارت ویزیت لمینت', verbose_name='خلاصه محتویات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('packed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='انباردار')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='core.ordershipment', verbose_name='مرسوله')),
            ],
            options={
                'verbose_name': 'بسته/کارتن',
                'verbose_name_plural': 'بسته\u200cها و لیبل\u200cها',
                'unique_together': {('shipment', 'box_number')},
            },
        ),
    ]
