# Generated by Django 5.2.9 on 2025-12-08 18:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_deliverymethod_invoicestatus_ordercosttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان محدوده')),
                ('code', models.SlugField(help_text='مطابق با group در OrderStatus (مثلا: design)', unique=True, verbose_name='کد سیستمی')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'محدوده دسترسی',
                'verbose_name_plural': 'محدوده\u200cهای دسترسی',
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_order_items', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس مسئول (طراح)'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='آیا نقش برای ادمین است؟'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='group',
            field=models.CharField(choices=[('admin', 'ادمین'), ('financial', 'مالی'), ('design', 'طراحی'), ('qc', 'کنترل کیفی'), ('production', 'تولید و چاپ'), ('logistics', 'ارسال و تحویل'), ('other', 'سایر')], default='other', max_length=20, verbose_name='گروه وضعیت'),
        ),
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ab72d9ab-1471-476e-bda0-e526d235f692'), unique=True, verbose_name='کد سیستمی'),
        ),
        migrations.AddField(
            model_name='role',
            name='scopes',
            field=models.ManyToManyField(blank=True, related_name='roles', to='core.accessscope', verbose_name='محدوده\u200cهای مجاز'),
        ),
    ]
