# Generated by Django 5.2.14 on 2026-06-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_product_price_alter_product_show_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfield',
            name='numeric_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='مقدار عددی پایه (برای فرمول این محصول)'),
        ),
        migrations.AlterField(
            model_name='productfieldchoice',
            name='numeric_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='مقدار عددی (ارزش این گزینه در این محصول)'),
        ),
    ]
