# Generated by Django 5.2.9 on 2025-12-08 20:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_accessscope_orderitem_assigned_to_role_is_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان گروه')),
                ('code', models.SlugField(help_text='شناسه یکتا برای لاجیک سیستم (مثلا: design)', unique=True, verbose_name='کد سیستمی')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'گروه وضعیت',
                'verbose_name_plural': 'گروه\u200cهای وضعیت',
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.SlugField(default=uuid.UUID('36706626-90b7-47fd-9d62-086d2bd3720f'), unique=True, verbose_name='کد سیستمی'),
        ),
    ]
