# Generated by Django 5.2.9 on 2025-12-08 20:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_orderstatusgroup_alter_order_options_alter_role_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_status', to='core.orderstatusgroup'),
        ),
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.SlugField(default=uuid.UUID('5524bba4-b92b-4aa7-a799-eec5dab1f8ee'), unique=True, verbose_name='کد سیستمی'),
        ),
    ]
