# Generated by Django 5.2.9 on 2025-12-08 20:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_orderstatus_group_alter_role_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.SlugField(default=uuid.UUID('54768ba0-a2b7-47af-8aef-82201235c832'), unique=True, verbose_name='کد سیستمی'),
        ),
    ]
