# Generated by Django 5.2.9 on 2025-12-09 09:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_role_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemfile',
            name='status',
            field=models.CharField(choices=[('uploading', 'در حال آپلود/پردازش'), ('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده (نیازمند اصلاح)')], default='pending', max_length=20, verbose_name='وضعیت فایل'),
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='group',
        ),
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.SlugField(default=uuid.UUID('071426b3-f69a-41b5-b9b4-38b10987f728'), unique=True, verbose_name='کد سیستمی'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='group',
            field=models.ManyToManyField(blank=True, related_name='order_status', to='core.orderstatusgroup'),
        ),
    ]
