# Generated by Django 5.2.9 on 2025-12-09 09:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_orderitemfile_status_remove_orderstatus_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmaterial',
            name='material',
        ),
        migrations.RemoveField(
            model_name='productmaterial',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productmaterial',
            name='user',
        ),
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.SlugField(default=uuid.UUID('82bdca2d-8c19-466c-8bb5-6c85aaa23d84'), unique=True, verbose_name='کد سیستمی'),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.DeleteModel(
            name='ProductMaterial',
        ),
    ]
