# Generated by Django 5.2.9 on 2025-12-09 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_productmaterial_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='group',
        ),
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='کد سیستمی'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_status', to='core.orderstatusgroup'),
        ),
    ]
