# Generated by Django 5.2.9 on 2025-12-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_orderstatus_group_alter_role_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='ترتیب قرارگیری در لیست (کم به زیاد).', verbose_name='ترتیب نمایش'),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='status_type',
            field=models.CharField(choices=[('initial', 'آغازین (Start)'), ('progress', 'در جریان (Progress)'), ('approve', 'تاییدیه (Approve)'), ('reject', 'رد شده (Reject)'), ('cancel', 'لغو شده (Cancel)')], default='progress', max_length=20, verbose_name='نوع وضعیت'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='internal_code',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='کد سیستمی'),
        ),
    ]
