# Generated by Django 5.2.9 on 2025-12-10 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_orderstatus_sort_order_orderstatus_status_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercostitem',
            options={'verbose_name': 'قلم هزینه', 'verbose_name_plural': 'اقلام هزینه'},
        ),
        migrations.RemoveField(
            model_name='ordercostitem',
            name='cost_type',
        ),
        migrations.RemoveField(
            model_name='ordercostitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ordercostitem',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ordercostitem',
            name='is_approved_by_finance',
        ),
        migrations.RemoveField(
            model_name='ordercostitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordercostitem',
            name='order_item',
        ),
        migrations.RemoveField(
            model_name='ordercostitem',
            name='title',
        ),
        migrations.RemoveField(
            model_name='ordercostitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ordercostitem',
            name='custom_title',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان (متفرقه)'),
        ),
        migrations.AlterField(
            model_name='ordercostitem',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='ordercostitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات تکمیلی'),
        ),
        migrations.CreateModel(
            name='OrderCostCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='شرح استاندارد')),
                ('code', models.CharField(max_length=150, unique=True, verbose_name='کد کالا/خدمت')),
                ('is_active', models.BooleanField(default=True)),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ordercosttype', verbose_name='دسته حسابداری')),
            ],
        ),
        migrations.AddField(
            model_name='ordercostitem',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ordercostcatalog', verbose_name='شرح هزینه'),
        ),
        migrations.CreateModel(
            name='OrderCostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان گزارش')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات کلی')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='orders/reports/%Y/%m/', verbose_name='فایل پیوست/سند')),
                ('is_approved_by_finance', models.BooleanField(default=False, verbose_name='تایید مالی')),
                ('finance_note', models.TextField(blank=True, verbose_name='یادداشت مالی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_reports', to='core.order', verbose_name='سفارش مرتبط')),
            ],
            options={
                'verbose_name': 'گزارش مالی',
                'verbose_name_plural': 'گزارشات مالی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ordercostitem',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.ordercostreport', verbose_name='گزارش مرتبط'),
        ),
    ]
