# Generated by Django 5.2.9 on 2025-12-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_ordercostitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_task_based',
            field=models.BooleanField(default=False, help_text='اگر فعال باشد، کاربر فقط سفارشاتی را می\u200cبیند که مستقیماً به او Assign شده\u200cاند (مثل طراح). اگر غیرفعال باشد، کاربر همه سفارشات موجود در مرحله کاری خود را می\u200cبیند (مثل مالی/انبار).', verbose_name='وظیفه\u200cمحور (نیازمند تخصیص)'),
        ),
    ]
