# Generated by Django 5.2.9 on 2025-12-11 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_role_is_task_based'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('target_model__in', ['item', 'both'])), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='core.orderstatus', verbose_name='وضعیت آیتم'),
        ),
        migrations.AddField(
            model_name='orderstatusgroup',
            name='target_model',
            field=models.CharField(choices=[('order', 'مختص سفارش (Order Only)'), ('item', 'مختص اقلام (Item Only)'), ('both', 'مشترک (Both)')], default='order', help_text='مشخص می\u200cکند این وضعیت در کدام بخش نمایش داده شود.', max_length=10, verbose_name='محدوده کاربرد'),
        ),
        migrations.AlterField(
            model_name='order',
            name='current_status',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('target_model__in', ['order', 'both'])), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.orderstatus', verbose_name='وضعیت فعلی'),
        ),
    ]
