# Generated by Django 5.2.9 on 2025-12-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_orderitem_status_orderstatusgroup_target_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatusgroup',
            name='target_model',
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='target_model',
            field=models.CharField(choices=[('order', 'مختص سفارش (Order Only)'), ('item', 'مختص اقلام (Item Only)'), ('both', 'مشترک (Both)')], default='order', help_text='مشخص می\u200cکند این وضعیت در کدام بخش نمایش داده شود.', max_length=10, verbose_name='محدوده کاربرد'),
        ),
    ]
