# Generated by Django 5.2.9 on 2025-12-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_orderstatusgroup_target_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='can_view_all_orders',
            field=models.BooleanField(default=False, verbose_name='توانایی مشاهده همه سفارشات'),
        ),
    ]
