# Generated by Django 5.2.9 on 2025-12-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_userrole_can_view_all_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='can_view_all_orders',
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_all_orders',
            field=models.BooleanField(default=False, verbose_name='توانایی مشاهده همه سفارشات'),
        ),
    ]
