# Generated by Django 5.2.9 on 2025-12-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_remove_userrole_can_view_all_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='is_workflow_gate',
            field=models.BooleanField(default=False, help_text='آیا این وضعیت می\u200cتواند مقصد انتقال\u200cهای خاص (مثل QC) باشد؟', verbose_name='دسترسی چندگانه به وضعیت'),
        ),
    ]
