# Generated by Django 5.2.9 on 2025-12-12 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_invoice_created_at_invoice_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertransaction',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderitemfile',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='target_model',
        ),
        migrations.AddField(
            model_name='orderitemfile',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='تایید شده'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='related_invoice', to='core.order', verbose_name='سفارش مرتبط'),
        ),
        migrations.DeleteModel(
            name='OrderInvoice',
        ),
        migrations.DeleteModel(
            name='OrderTransaction',
        ),
    ]
