# Generated by Django 5.2.9 on 2025-12-13 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_remove_ordertransaction_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='is_admin',
        ),
    ]
