# Generated by Django 5.2.9 on 2025-12-13 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_role_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordercostreport',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='role',
            name='is_task_based',
        ),
        migrations.CreateModel(
            name='OrderCostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='financial/costs/attachments/%Y/%m/', verbose_name='فایل ضمیمه')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.ordercostreport', verbose_name='گزارش هزینه')),
            ],
            options={
                'verbose_name': 'پیوست هزینه',
                'verbose_name_plural': 'پیوست\u200cهای هزینه',
            },
        ),
        migrations.CreateModel(
            name='OrderPrintReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان گزارش')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات فنی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده (اپراتور)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_reports', to='core.order', verbose_name='سفارش مرتبط')),
            ],
            options={
                'verbose_name': 'گزارش مصرف چاپ',
                'verbose_name_plural': 'گزارشات مصرف چاپ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPrintItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('paper_gloss', 'کاغذ گلاسه'), ('paper_matte', 'کاغذ تحریر/مات'), ('paper_kraft', 'کاغذ کرافت'), ('zinc', 'زینک (پلیت)'), ('ink_cmyk', 'مرکب (CMYK)'), ('ink_special', 'مرکب خاص (پنتون)'), ('glue', 'چسب صحافی'), ('cell_matte', 'سلفون مات'), ('cell_gloss', 'سلفون براق'), ('other', 'سایر ملزومات')], default='other', max_length=50, verbose_name='نوع متریال')),
                ('custom_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.orderprintreport', verbose_name='گزارش مرتبط')),
            ],
            options={
                'verbose_name': 'قلم متریال',
                'verbose_name_plural': 'اقلام متریال',
            },
        ),
        migrations.CreateModel(
            name='OrderPrintAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/print_logs/%Y/%m/', verbose_name='فایل/عکس')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.orderprintreport', verbose_name='گزارش چاپ')),
            ],
            options={
                'verbose_name': 'پیوست چاپ',
                'verbose_name_plural': 'پیوست\u200cهای چاپ',
            },
        ),
    ]
