# Generated by Django 5.2.9 on 2025-12-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_ordercostreport_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='scopes',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='is_workflow_gate',
        ),
        migrations.RemoveField(
            model_name='role',
            name='can_view_all_orders',
        ),
        migrations.AddField(
            model_name='role',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='roles', to='core.orderstatusgroup', verbose_name='گروه\u200cهای وضعیت مجاز'),
        ),
        migrations.DeleteModel(
            name='AccessScope',
        ),
    ]
