# Generated by Django 5.2.9 on 2025-12-14 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_remove_role_scopes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='orderitemfile',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('rejected', 'رد شده (نیازمند اصلاح)'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت فایل'),
        ),
        migrations.AlterField(
            model_name='order',
            name='current_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.orderstatus', verbose_name='وضعیت فعلی'),
        ),
    ]
