# Generated by Django 5.2.9 on 2025-12-14 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alter_orderitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دسته')),
                ('slug', models.SlugField(unique=True, verbose_name='کد سیستمی')),
                ('cost_type', models.CharField(choices=[('design', 'طراحی'), ('print', 'چاپ'), ('material', 'مواد اولیه'), ('transport', 'حمل و نقل'), ('packing', 'بسته\u200cبندی'), ('storage', 'برون\u200cسپاری'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع هزینه')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'دسته هزینه',
                'verbose_name_plural': 'دسته\u200cهای هزینه',
            },
        ),
        migrations.RemoveField(
            model_name='ordercostcatalog',
            name='cost_type',
        ),
        migrations.RemoveField(
            model_name='ordercostreport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ordercostreport',
            name='order',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_type',
        ),
        migrations.AlterField(
            model_name='ordercostitem',
            name='catalog_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ordercostcategory', verbose_name='شرح هزینه'),
        ),
        migrations.AlterField(
            model_name='orderprintitem',
            name='material_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_items', to='core.ordercostcategory', verbose_name='نوع مواد اولیه'),
        ),
        migrations.CreateModel(
            name='OrderCostSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finalized', models.BooleanField(default=False, help_text='آیا محاسبه هزینه\u200cها تمام شده است؟', verbose_name='نهایی شده؟')),
                ('total_material_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='هزینه متریال')),
                ('total_operational_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='هزینه عملیاتی/خدمات')),
                ('total_outsourcing_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='هزینه برون\u200cسپاری')),
                ('total_overhead_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='هزینه سربار/متفرقه')),
                ('total_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='جمع کل هزینه\u200cها')),
                ('revenue_amount', models.DecimalField(decimal_places=0, default=0, help_text='مبلغ نهایی فاکتور مشتری', max_digits=18, verbose_name='مبلغ فروش (درآمد)')),
                ('net_profit', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='سود خالص')),
                ('profit_margin_percent', models.FloatField(default=0.0, verbose_name='حاشیه سود (%)')),
                ('admin_note', models.TextField(blank=True, verbose_name='یادداشت مدیریت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cost_sheets', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده مالی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_sheet_created_by', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheet', to='core.order', verbose_name='سفارش مرتبط')),
            ],
            options={
                'verbose_name': 'پرونده مالی سفارش',
                'verbose_name_plural': 'پرونده\u200cهای مالی سفارشات',
            },
        ),
        migrations.AlterField(
            model_name='ordercostattachment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.ordercostsheet', verbose_name='گزارش هزینه'),
        ),
        migrations.AlterField(
            model_name='ordercostitem',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.ordercostsheet', verbose_name='گزارش مرتبط'),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان استعلام')),
                ('quotation_number', models.CharField(max_length=50, unique=True, verbose_name='شماره استعلام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('valid_until', models.DateTimeField(help_text='این قیمت\u200cها تا کی معتبر هستند؟', verbose_name='تاریخ اعتبار')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('sent', 'ارسال شده برای مشتری'), ('accepted', 'تایید شده توسط مشتری'), ('rejected', 'رد شده'), ('expired', 'منقضی شده'), ('converted', 'تبدیل شده به سفارش')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ کل')),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مالیات')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='تخفیف')),
                ('final_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ قابل پرداخت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات / شرایط')),
                ('converted_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_quotation', to='core.order', verbose_name='سفارش تبدیل شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to=settings.AUTH_USER_MODEL, verbose_name='مشتری / درخواست کننده')),
            ],
            options={
                'verbose_name': 'استعلام قیمت',
                'verbose_name_plural': 'استعلام\u200cهای قیمت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='نام محصول/خدمت')),
                ('description', models.TextField(blank=True, verbose_name='شرح فنی')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='قیمت واحد')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.quotation', verbose_name='استعلام مرتبط')),
            ],
            options={
                'verbose_name': 'قلم استعلام',
                'verbose_name_plural': 'اقلام استعلام',
            },
        ),
        migrations.DeleteModel(
            name='OrderCostType',
        ),
        migrations.DeleteModel(
            name='OrderCostCatalog',
        ),
        migrations.DeleteModel(
            name='OrderCostReport',
        ),
    ]
