# Generated by Django 5.2.9 on 2025-12-14 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_ordercostcategory_remove_ordercostcatalog_cost_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercostsheet',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی'),
        ),
        migrations.AddField(
            model_name='ordercostsheet',
            name='title',
            field=models.CharField(default=1, help_text='مثلا: هزینه\u200cهای واحد چاپ', max_length=200, verbose_name='عنوان گزارش'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordercostsheet',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cost_sheets', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
    ]
