# Generated by Django 5.2.9 on 2025-12-14 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_ordercostsheet_description_ordercostsheet_title_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercostsheet',
            options={'verbose_name': 'سند بهای تمام شده', 'verbose_name_plural': 'اسناد بهای تمام شده'},
        ),
        migrations.RemoveField(
            model_name='ordercostsheet',
            name='admin_note',
        ),
        migrations.RemoveField(
            model_name='ordercostsheet',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='ordercostsheet',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ordercostsheet',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ordercostsheet',
            name='is_finalized',
        ),
        migrations.RemoveField(
            model_name='ordercostsheet',
            name='title',
        ),
        migrations.RemoveField(
            model_name='ordercostsheet',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='ordercostsheet',
            name='total_operational_cost',
        ),
        migrations.RemoveField(
            model_name='ordercostsheet',
            name='total_outsourcing_cost',
        ),
        migrations.AddField(
            model_name='ordercostsheet',
            name='final_total_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='بهای تمام شده کل'),
        ),
        migrations.AddField(
            model_name='ordercostsheet',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='اگر تیک بخورد، هیچ گزارشی دیگر قابل اضافه شدن نیست (پایان سال مالی یا تسویه نهایی).', verbose_name='قفل شده؟'),
        ),
        migrations.AddField(
            model_name='ordercostsheet',
            name='total_service_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='جمع هزینه خدمات/چاپ'),
        ),
        migrations.AddField(
            model_name='ordercostsheet',
            name='total_shipping_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='جمع هزینه ارسال'),
        ),
        migrations.AlterField(
            model_name='ordercostsheet',
            name='net_profit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='سود/زیان خالص'),
        ),
        migrations.AlterField(
            model_name='ordercostsheet',
            name='revenue_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ فروش (فاکتور)'),
        ),
        migrations.AlterField(
            model_name='ordercostsheet',
            name='total_material_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='جمع هزینه مواد'),
        ),
        migrations.AlterField(
            model_name='ordercostsheet',
            name='total_overhead_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='جمع سربار/سایر'),
        ),
        migrations.CreateModel(
            name='OrderCostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثلا: هزینه کاغذ مصرفی بخش افست', max_length=200, verbose_name='عنوان گزارش')),
                ('department', models.CharField(choices=[('design', 'واحد طراحی'), ('production', 'واحد تولید/چاپ'), ('warehouse', 'انبار'), ('logistics', 'لجستیک و ارسال'), ('outsourcing', 'برون\u200cسپاری'), ('management', 'مدیریت (سربار)')], max_length=20, verbose_name='دپارتمان')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.ordercostsheet', verbose_name='سند مادر')),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ارسال کننده گزارش')),
            ],
            options={
                'verbose_name': 'گزارش هزینه داخلی',
                'verbose_name_plural': 'گزارشات هزینه داخلی',
                'ordering': ['-created_at'],
            },
        ),
    ]
