# Generated by Django 5.2.9 on 2025-12-14 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_ordercostsheet_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercostitem',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.ordercostreport', verbose_name='گزارش مرتبط'),
        ),
    ]
