# Generated by Django 5.2.9 on 2025-12-14 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_ordercostitem_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercostattachment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.ordercostreport', verbose_name='گزارش هزینه'),
        ),
    ]
