# Generated by Django 5.2.9 on 2025-12-14 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_ordercostattachment_report'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicestatus',
            options={'verbose_name': 'وضعیت فاکتور', 'verbose_name_plural': 'وضعیت\u200cهای فاکتور'},
        ),
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-created_at'], 'verbose_name': 'پیش\u200cفاکتور قیمت', 'verbose_name_plural': 'پیش\u200cفاکتور\u200cهای قیمت'},
        ),
        migrations.AlterModelOptions(
            name='quotationitem',
            options={'verbose_name': 'قلم پیش\u200cفاکتور', 'verbose_name_plural': 'اقلام پیش\u200cفاکتور'},
        ),
        migrations.RemoveField(
            model_name='invoicestatus',
            name='color',
        ),
        migrations.RemoveField(
            model_name='invoicestatus',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotation_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='شماره پیش\u200cفاکتور'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان پیش\u200cفاکتور'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.quotation', verbose_name='پیش\u200cفاکتور مرتبط'),
        ),
    ]
