# Generated by Django 5.2.9 on 2025-12-14 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_invoicestatus_options_alter_quotation_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuotationItem',
        ),
    ]
