# Generated by Django 5.2.9 on 2025-12-15 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_quotation_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='dest_account',
            field=models.CharField(blank=True, help_text='مثلا: بانک ملت - جاری', max_length=100, null=True, verbose_name='واریز به حساب'),
        ),
    ]
