# Generated by Django 5.2.9 on 2025-12-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_transaction_dest_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('PAID_PARTIAL', 'پرداخت ناقص'), ('PAID_FULL', 'تسویه کامل'), ('CANCELED', 'لغو شده'), ('FINALIZE', 'نهایی شده / بسته شده')], db_index=True, default='PENDING', max_length=20, verbose_name='وضعیت جاری'),
        ),
        migrations.AlterField(
            model_name='invoicestatelog',
            name='to_status',
            field=models.CharField(max_length=50, verbose_name='به وضعیت'),
        ),
        migrations.AlterField(
            model_name='invoicestatelog',
            name='from_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='از وضعیت'),
        ),
        migrations.DeleteModel(
            name='InvoiceStatus',
        ),
    ]
