# Generated by Django 5.2.9 on 2025-12-15 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_invoice_status_alter_invoicestatelog_to_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicestatelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='تغییر دهنده'),
        ),
    ]
