# Generated by Django 5.2.9 on 2025-12-15 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_invoicestatelog_invoice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotation',
            options={'ordering': ['-created_at'], 'verbose_name': 'پیش\u200cفاکتور', 'verbose_name_plural': 'پیش\u200cفاکتورها'},
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='quotation',
            name='items_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='جمع اقلام'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='services_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='جمع خدمات'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='final_amount',
            field=models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ قابل پرداخت'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ قطعی شدن'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='items_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='جمع اقلام'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='core.order', verbose_name='سفارش مرتبط'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='services_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='جمع خدمات'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار پرداخت'), ('PAID_PARTIAL', 'پرداخت ناقص'), ('PAID_FULL', 'تسویه کامل'), ('CANCELED', 'لغو شده'), ('FINALIZE', 'نهایی شده / بسته شده')], db_index=True, default='PENDING', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='final_amount',
            field=models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ قابل پرداخت'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('sent', 'ارسال شده'), ('accepted', 'تایید شده'), ('rejected', 'رد شده'), ('expired', 'منقضی شده'), ('converted', 'تبدیل شده به سفارش')], default='draft', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to=settings.AUTH_USER_MODEL, verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='valid_until',
            field=models.DateTimeField(verbose_name='تاریخ اعتبار'),
        ),
    ]
