# Generated by Django 5.2.9 on 2025-12-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_alter_quotation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='final_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ قابل پرداخت'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='final_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ قابل پرداخت'),
        ),
    ]
