# Generated by Django 5.2.9 on 2025-12-16 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_invoice_final_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='final_amount',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='items_amount',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='services_amount',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='title',
        ),
        migrations.AddField(
            model_name='quotation',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تخمینی تحویل'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='product_name',
            field=models.CharField(max_length=255, null=True, verbose_name='نام محصول'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='product_snapshot',
            field=models.JSONField(blank=True, default=dict, help_text='شامل ابعاد، متریال، آپشن\u200cها و ویژگی\u200cهای انتخابی در لحظه صدور', null=True, verbose_name='جزئیات پیکربندی (Snapshot)'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='تیراژ'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ کل'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ به روزرسانی'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='معتبر تا تاریخ'),
        ),
    ]
