# Generated by Django 5.2.9 on 2025-12-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_remove_quotation_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='user',
        ),
        migrations.AddField(
            model_name='quotation',
            name='customer_name',
            field=models.CharField(max_length=255, null=True, verbose_name='نام مشتری'),
        ),
    ]
