# Generated by Django 5.2.9 on 2025-12-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_remove_quotation_user_quotation_customer_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderpackage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderpackage',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='orderpackage',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام مشتری'),
        ),
        migrations.AddField(
            model_name='orderpackage',
            name='order_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر سفارش'),
        ),
        migrations.AddField(
            model_name='orderpackage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس'),
        ),
        migrations.RemoveField(
            model_name='orderpackage',
            name='box_number',
        ),
        migrations.RemoveField(
            model_name='orderpackage',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='orderpackage',
            name='length_cm',
        ),
        migrations.RemoveField(
            model_name='orderpackage',
            name='weight_grams',
        ),
        migrations.RemoveField(
            model_name='orderpackage',
            name='width_cm',
        ),
    ]
