# Generated by Django 5.2.9 on 2025-12-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_alter_orderpackage_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpackage',
            name='label_uuid',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='شناسه لیبل'),
        ),
    ]
