# Generated by Django 5.2.9 on 2025-12-16 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_alter_orderpackage_label_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='quotations/products/%Y/%m/%d/', verbose_name='تصویر محصول'),
        ),
        migrations.CreateModel(
            name='OrderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='تاریخ شروع فرآیند')),
                ('due_date', models.DateTimeField(verbose_name='تاریخ تحویل نهایی (Deadline)')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل واقعی')),
                ('schedule_notes', models.TextField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False, help_text='اگر قفل شود، تاریخ\u200cها به صورت خودکار تغییر نمی\u200cکنند')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='core.order')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('due_date', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='core.orderschedule')),
            ],
        ),
        migrations.AddIndex(
            model_name='orderschedule',
            index=models.Index(fields=['start_date', 'due_date'], name='core_orders_start_d_5f5a74_idx'),
        ),
    ]
