# Generated by Django 5.2.9 on 2025-12-17 14:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_quotation_product_image_orderschedule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulemilestone',
            name='schedule',
        ),
        migrations.AlterModelOptions(
            name='orderschedule',
            options={'verbose_name': 'زمان\u200cبندی سفارش', 'verbose_name_plural': 'زمان\u200cبندی\u200cهای سفارش'},
        ),
        migrations.RemoveField(
            model_name='orderschedule',
            name='is_locked',
        ),
        migrations.RemoveField(
            model_name='orderschedule',
            name='schedule_notes',
        ),
        migrations.AddField(
            model_name='orderschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orderschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderschedule',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='core.order', verbose_name='سفارش مرتبط'),
        ),
        migrations.AlterField(
            model_name='orderschedule',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع فرآیند'),
        ),
        migrations.AddIndex(
            model_name='orderschedule',
            index=models.Index(fields=['completed_at'], name='core_orders_complet_540fbc_idx'),
        ),
        migrations.DeleteModel(
            name='ScheduleMilestone',
        ),
    ]
