# Generated by Django 5.2.9 on 2025-12-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_remove_schedulemilestone_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershipment',
            name='delivery_method',
            field=models.CharField(choices=[('terminal', 'باربری ترمینال)'), ('pickup', 'تحویل حضوری(درب کارگاه)'), ('other', 'سایر')], default='other', max_length=50, verbose_name='روش ارسال'),
        ),
        migrations.DeleteModel(
            name='DeliveryMethod',
        ),
    ]
