# Generated by Django 5.2.9 on 2025-12-18 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0069_alter_ordershipment_delivery_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatelog',
            name='from_status',
        ),
        migrations.RemoveField(
            model_name='orderstatelog',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderstatelog',
            name='to_status',
        ),
        migrations.RemoveField(
            model_name='orderstatelog',
            name='user',
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='delivery_method',
            field=models.CharField(choices=[('terminal', 'باربری ترمینال'), ('pickup', 'تحویل حضوری(درب کارگاه)'), ('other', 'سایر')], default='other', max_length=50, verbose_name='روش ارسال'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('CREATE', 'ایجاد'), ('UPDATE', 'ویرایش'), ('DELETE', 'حذف'), ('LOGIN', 'ورود به سیستم'), ('LOGOUT', 'خروج'), ('approve', 'تایید کردن'), ('reject', 'رد کردن'), ('change_pass', 'تغییر رمز عبور'), ('assignment', 'تخصیص وظیفه')], db_index=True, max_length=20, verbose_name='نوع عملیات')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='تغییرات داده\u200cای')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات سیستمی/دستی')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser Info', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ سیستم',
                'verbose_name_plural': 'لاگ\u200cهای سیستم',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='InvoiceStateLog',
        ),
        migrations.DeleteModel(
            name='OrderStateLog',
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='core_auditl_content_fec0c4_idx'),
        ),
    ]
