# Generated by Django 5.2.9 on 2025-12-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_alter_auditlog_content_type_alter_auditlog_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfileuploadrequirement',
            name='allowed_aspect_ratios',
            field=models.JSONField(blank=True, default=list, help_text='لیستی از نسبت\u200cهای تصویر مجاز را انتخاب کنید', null=True, verbose_name='نسبت\u200cهای تصویر مجاز'),
        ),
    ]
