# Generated by Django 5.2.9 on 2025-12-20 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='admin_reply',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ ادمین'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پاسخ'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='replied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='پاسخ دهنده'),
        ),
    ]
