# Generated by Django 5.2.9 on 2025-12-21 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_contactus_admin_reply_contactus_replied_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfileuploadrequirement',
            name='spec',
        ),
        migrations.AlterUniqueTogether(
            name='productfileuploadrequirement',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='productfileuploadrequirement',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitemfile',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='cartitemupload',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='option',
            name='input_type',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='pricing_strategy',
        ),
        migrations.RemoveField(
            model_name='productoptionvalue',
            name='is_step_ceiling',
        ),
        migrations.RemoveField(
            model_name='productoptionvalue',
            name='quantity_step',
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_unit',
            field=models.PositiveIntegerField(default=1, help_text='قیمت بالا به ازای چه تعدادی است؟ (مثلا: ۱۰۰۰ تومان به ازای هر ۱۰ عدد).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='گام شمارش (تعداد مبنا)'),
        ),
        migrations.DeleteModel(
            name='FileUploadSpec',
        ),
        migrations.DeleteModel(
            name='ProductFileUploadRequirement',
        ),
    ]
