# Generated by Django 5.2.9 on 2025-12-21 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_contactus_admin_reply_contactus_replied_at_and_more'),
    ]

    # operations لیست اصلاح شده:

    operations = [
        # 1. اول قید یکتایی را بردارید (تا وقتی فیلدها هنوز هستند، ایندکس پاک شود)
        migrations.AlterUniqueTogether(
            name='productfileuploadrequirement',
            unique_together=set(),
        ),
        
        # 2. حالا وابستگی‌های خارجی را حذف کنید (Foreign Keyهایی که به این مدل اشاره دارند)
        # این‌ها باید قبل از حذف خود مدل انجام شوند
        migrations.RemoveField(
            model_name='orderitemfile',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='cartitemupload',
            name='requirement',
        ),

        # 3. حالا می‌توانید فیلدهای داخلی مدل را حذف کنید (یا کلاً ننویسید چون DeleteModel همه را پاک می‌کند)
        # اما اگر می‌خواهید نگه دارید، ترتیبش مهم نیست چون UniqueTogether حل شد.
        migrations.RemoveField(
            model_name='productfileuploadrequirement',
            name='spec',
        ),
        migrations.RemoveField(
            model_name='productfileuploadrequirement',
            name='product',
        ),

        # 4. سایر تغییرات مدل‌های دیگر
        migrations.RemoveField(
            model_name='option',
            name='input_type',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='pricing_strategy',
        ),
        migrations.RemoveField(
            model_name='productoptionvalue',
            name='is_step_ceiling',
        ),
        migrations.RemoveField(
            model_name='productoptionvalue',
            name='quantity_step',
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_unit',
            field=models.PositiveIntegerField(default=1, help_text='قیمت بالا به ازای چه تعدادی است؟ (مثلا: ۱۰۰۰ تومان به ازای هر ۱۰ عدد).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='گام شمارش (تعداد مبنا)'),
        ),
        
        # 5. در نهایت حذف کامل مدل‌ها
        migrations.DeleteModel(
            name='FileUploadSpec',
        ),
        migrations.DeleteModel(
            name='ProductFileUploadRequirement',
        ),
    ]