# Generated by Django 5.2.9 on 2025-12-21 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_remove_productfileuploadrequirement_spec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_modifier_percent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_per_square_unit',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='has_pricing',
        ),
        migrations.AddField(
            model_name='optionvalue',
            name='input_type',
            field=models.CharField(choices=[('text', 'ورودی متنی (Text)'), ('textarea', 'ورودی متن بلند (Textarea)'), ('number', 'ورودی عددی (Number)'), ('select', 'لیست کشویی (Select)'), ('radio', 'رادیو باتن (Radio)'), ('checkbox', 'چک\u200cباکس چندتایی (Checkbox)'), ('boolean', 'سوییچ / تیک (Boolean)')], default='text', max_length=25, verbose_name='نوع ویژگی'),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='value',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='کد سیستمی'),
        ),
        migrations.AlterField(
            model_name='productattachment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attachment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ْإimage', to='core.product'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.product'),
        ),
        migrations.AlterField(
            model_name='productpricingconfig',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_config', to='core.product', verbose_name='محصول مرتبط'),
        ),
        migrations.AlterField(
            model_name='productquantity',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_quantity', to='core.product'),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_size', to='core.product'),
        ),
    ]
