# Generated by Django 5.2.9 on 2025-12-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_alter_address_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionvalue',
            name='input_type',
            field=models.CharField(choices=[('text', 'ورودی متنی (Text)'), ('textarea', 'ورودی متن بلند (Textarea)'), ('number', 'ورودی عددی (Number)'), ('select', 'لیست کشویی (Select)'), ('radio', 'رادیو باتن (Radio)'), ('checkbox', 'چک\u200cباکس چندتایی (Checkbox)'), ('multi_select', 'انتخاب چندگانه (Multi Select / Checkboxes)')], default='text', max_length=25, verbose_name='نوع ویژگی'),
        ),
    ]
