# Generated by Django 5.2.9 on 2025-12-22 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_alter_optionvalue_input_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_configs', to='core.option'),
        ),
        migrations.AlterField(
            model_name='productoptionvalue',
            name='global_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.optionvalue', verbose_name='کپی از الگوی گلوبال'),
        ),
        migrations.AlterField(
            model_name='productoptionvalue',
            name='product_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.productoption'),
        ),
    ]
