# Generated by Django 5.2.9 on 2025-12-23 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_productoption_option_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productoption',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='optionvalue',
            name='input_type',
        ),
        migrations.AddField(
            model_name='option',
            name='guide_text',
            field=models.TextField(blank=True, help_text='متنی که با کلیک روی آیکون مربوطه نمایش داده می\u200cشود.', null=True, verbose_name='متن راهنما/هشدار'),
        ),
        migrations.AddField(
            model_name='option',
            name='guide_type',
            field=models.CharField(choices=[('info', 'اطلاعات'), ('warning', 'هشدار'), ('tip', 'نکته)')], default='info', help_text='رنگ و آیکون نمایش داده شده را تعیین می\u200cکند.', max_length=20, verbose_name='نوع پیام'),
        ),
        migrations.AddField(
            model_name='option',
            name='input_type',
            field=models.CharField(choices=[('text', 'ورودی متنی (Text)'), ('textarea', 'ورودی متن بلند (Textarea)'), ('number', 'ورودی عددی (Number)'), ('select', 'لیست کشویی (Select)'), ('radio', 'رادیو باتن (Radio)'), ('checkbox', 'چک\u200cباکس چندتایی (Checkbox)'), ('multi_select', 'انتخاب چندگانه (Multi Select / Checkboxes)')], default='select', max_length=25, verbose_name='نوع ورودی'),
        ),
        migrations.AddField(
            model_name='optionvalue',
            name='guide_text',
            field=models.TextField(blank=True, help_text='متنی که با کلیک روی آیکون مربوطه نمایش داده می\u200cشود.', null=True, verbose_name='متن راهنما/هشدار'),
        ),
        migrations.AddField(
            model_name='optionvalue',
            name='guide_type',
            field=models.CharField(choices=[('info', 'اطلاعات'), ('warning', 'هشدار'), ('tip', 'نکته)')], default='info', help_text='رنگ و آیکون نمایش داده شده را تعیین می\u200cکند.', max_length=20, verbose_name='نوع پیام'),
        ),
        migrations.AddField(
            model_name='product',
            name='guide_text',
            field=models.TextField(blank=True, help_text='متنی که با کلیک روی آیکون مربوطه نمایش داده می\u200cشود.', null=True, verbose_name='متن راهنما/هشدار'),
        ),
        migrations.AddField(
            model_name='product',
            name='guide_type',
            field=models.CharField(choices=[('info', 'اطلاعات'), ('warning', 'هشدار'), ('tip', 'نکته)')], default='info', help_text='رنگ و آیکون نمایش داده شده را تعیین می\u200cکند.', max_length=20, verbose_name='نوع پیام'),
        ),
        migrations.AddField(
            model_name='productattachment',
            name='guide_text',
            field=models.TextField(blank=True, help_text='متنی که با کلیک روی آیکون مربوطه نمایش داده می\u200cشود.', null=True, verbose_name='متن راهنما/هشدار'),
        ),
        migrations.AddField(
            model_name='productattachment',
            name='guide_type',
            field=models.CharField(choices=[('info', 'اطلاعات'), ('warning', 'هشدار'), ('tip', 'نکته)')], default='info', help_text='رنگ و آیکون نمایش داده شده را تعیین می\u200cکند.', max_length=20, verbose_name='نوع پیام'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='guide_text',
            field=models.TextField(blank=True, help_text='متنی که با کلیک روی آیکون مربوطه نمایش داده می\u200cشود.', null=True, verbose_name='متن راهنما/هشدار'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='guide_type',
            field=models.CharField(choices=[('info', 'اطلاعات'), ('warning', 'هشدار'), ('tip', 'نکته)')], default='info', help_text='رنگ و آیکون نمایش داده شده را تعیین می\u200cکند.', max_length=20, verbose_name='نوع پیام'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='input_type',
            field=models.CharField(choices=[('text', 'ورودی متنی (Text)'), ('textarea', 'ورودی متن بلند (Textarea)'), ('number', 'ورودی عددی (Number)'), ('select', 'لیست کشویی (Select)'), ('radio', 'رادیو باتن (Radio)'), ('checkbox', 'چک\u200cباکس چندتایی (Checkbox)'), ('multi_select', 'انتخاب چندگانه (Multi Select / Checkboxes)')], default='select', max_length=25, verbose_name='نوع ورودی'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='label',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان نمایشی'),
        ),
        migrations.AddField(
            model_name='productoption',
            name='name',
            field=models.CharField(default=1, help_text='شناسه یکتا برای کدنویسی (مثال: paper_type)', max_length=150, verbose_name='نام سیستمی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productoptionvalue',
            name='guide_text',
            field=models.TextField(blank=True, help_text='متنی که با کلیک روی آیکون مربوطه نمایش داده می\u200cشود.', null=True, verbose_name='متن راهنما/هشدار'),
        ),
        migrations.AddField(
            model_name='productoptionvalue',
            name='guide_type',
            field=models.CharField(choices=[('info', 'اطلاعات'), ('warning', 'هشدار'), ('tip', 'نکته)')], default='info', help_text='رنگ و آیکون نمایش داده شده را تعیین می\u200cکند.', max_length=20, verbose_name='نوع پیام'),
        ),
        migrations.AddField(
            model_name='productquantity',
            name='guide_text',
            field=models.TextField(blank=True, help_text='متنی که با کلیک روی آیکون مربوطه نمایش داده می\u200cشود.', null=True, verbose_name='متن راهنما/هشدار'),
        ),
        migrations.AddField(
            model_name='productquantity',
            name='guide_type',
            field=models.CharField(choices=[('info', 'اطلاعات'), ('warning', 'هشدار'), ('tip', 'نکته)')], default='info', help_text='رنگ و آیکون نمایش داده شده را تعیین می\u200cکند.', max_length=20, verbose_name='نوع پیام'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='guide_text',
            field=models.TextField(blank=True, help_text='متنی که با کلیک روی آیکون مربوطه نمایش داده می\u200cشود.', null=True, verbose_name='متن راهنما/هشدار'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='guide_type',
            field=models.CharField(choices=[('info', 'اطلاعات'), ('warning', 'هشدار'), ('tip', 'نکته)')], default='info', help_text='رنگ و آیکون نمایش داده شده را تعیین می\u200cکند.', max_length=20, verbose_name='نوع پیام'),
        ),
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(help_text='شناسه یکتا برای کدنویسی (مثال: paper_type)', max_length=150, verbose_name='نام سیستمی'),
        ),
        migrations.AlterField(
            model_name='optionvalue',
            name='value',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='کد سیستمی/مقدار'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_configs', to='core.option'),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='core.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productoptionvalue',
            name='global_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.optionvalue', verbose_name='منبع گلوبال'),
        ),
        migrations.AlterField(
            model_name='productoptionvalue',
            name='has_pricing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productoptionvalue',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productoptionvalue',
            name='label',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان مقدار'),
        ),
        migrations.AlterField(
            model_name='productoptionvalue',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productoptionvalue',
            name='price_impact',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='productoptionvalue',
            name='value',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='کد سیستمی/مقدار'),
        ),
    ]
