# Generated by Django 5.2.9 on 2025-12-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_cartitem_description_cartitem_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='description',
        ),
    ]
