services:
  # ====== Database ====== #
  db:
    image: postgres:17-alpine
    container_name: printoo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./env/.env.dev
    networks:
      - data_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ====== Redis ====== #
  redis:
    image: redis:7-alpine
    container_name: printoo_redis
    networks:
      - data_network

# ====== Networks Configuration ====== #
networks:
  data_network:
    driver: bridge
    name: printoo_shared_data_network

volumes:
  postgres_data: