version: '3.8'

services:
  # ====== Backend (Production) ====== #
  backend:
    build:
      context: .
      dockerfile: backend/dockerfiles/prod/Dockerfile
    container_name: printoo_backend
    volumes:
      - ./backend/media:/app/media
    ports:
      - "9010:9010"
    env_file:
      - ./env/.env.prod
    networks:
      - shared_data_net
      - backend_net
    restart: always

  # ====== Celery Workers ====== #
  celery_worker:
    build:
      context: .
      dockerfile: backend/dockerfiles/prod/Dockerfile
    container_name: printoo_celery
    command: celery -A backend.celery worker -l info
    volumes:
      - ./backend/media:/app/media
    env_file:
      - ./env/.env.prod
    networks:
      - shared_data_net
    restart: always

  # ====== Frontend (Nginx) ====== #
  frontend:
    build:
      context: ./frontend/react-js
      dockerfile: Dockerfile.prod
    container_name: printoo_frontend
    ports:
      - "80:80"
    restart: always
    networks: 
      - backend_net

networks:
  backend_net:
    driver: bridge
  shared_data_net:
    external: true
    name: printoo_shared_data_network