version: '3.8'

services:
  # ====== Customer Backend (Production) ====== #
  customer_site:
    build:
      context: .
      # حتماً داکرفایل پروداکشن که در ادامه می‌گذارم را در این مسیر بسازید
      dockerfile: backend/services/customer_site/dockerfiles/prod/Dockerfile
    container_name: printoo_customer_site
    # در پروداکشن command را حذف می‌کنیم تا از CMD داخل داکرفایل (Gunicorn) استفاده شود
    volumes:
      - ./backend/services/customer_site/media:/app/media
    ports:
      - "9010:9010"
    environment:
      - PYTHONPATH=/app/shared_libs:$PYTHONPATH
    env_file:
      - ./env/.env.prod
    networks:
      - shared_data_net
      - customer_net
    restart: always

  # ====== Celery Workers ====== #
  celery_worker_customer:
    build:
      context: .
      dockerfile: backend/services/customer_site/dockerfiles/prod/Dockerfile
    container_name: printoo_celery_customer
    command: celery -A customer_site.celery worker -l info
    volumes:
      - ./backend/services/customer_site/media:/app/media
    environment:
      - PYTHONPATH=/app/shared_libs:$PYTHONPATH
    env_file:
      - ./env/.env.prod
    networks:
      - shared_data_net
    restart: always

  # ====== Frontend (Nginx) ====== #
  frontend:
    build:
      context: ./frontend/react-js
      dockerfile: Dockerfile.prod
    container_name: printoo_frontend
    ports:
      - "80:80" # پورت استاندارد وب
    restart: always
    networks: 
      - customer_net

networks:
  customer_net:
    driver: bridge
  shared_data_net:
    external: true
    name: printoo_shared_data_network
