# Generated by Django 5.2.9 on 2025-12-25 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'ایجاد'), ('UPDATE', 'ویرایش'), ('DELETE', 'حذف'), ('LOGIN', 'ورود به سیستم'), ('LOGOUT', 'خروج'), ('approve', 'تایید کردن'), ('reject', 'رد کردن'), ('change_pass', 'تغییر رمز عبور'), ('assignment', 'تخصیص وظیفه')], db_index=True, max_length=20, verbose_name='نوع عملیات')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='تغییرات داده\u200cای')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات سیستمی/دستی')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Browser Info', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ سیستم',
                'verbose_name_plural': 'لاگ\u200cهای سیستم',
                'db_table': 'admin_audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='admin_audit_content_ebb283_idx')],
            },
        ),
    ]
