# Generated by Django 5.2.11 on 2026-02-24 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0019_productfieldchoice_is_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی مقاله',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای مقالات',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='اسلاگ')),
                ('summary', models.TextField(help_text='برای نمایش در لیست مقالات', verbose_name='خلاصه مقاله')),
                ('content', models.TextField(verbose_name='متن کامل')),
                ('image', models.ImageField(upload_to='blog/covers/', verbose_name='تصویر کاور')),
                ('meta_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان سئو (Meta Title)')),
                ('meta_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات سئو (Meta Description)')),
                ('tags', models.CharField(blank=True, help_text='با کاما جدا کنید', max_length=255, verbose_name='تگ\u200cها')),
                ('read_time', models.PositiveSmallIntegerField(default=5, verbose_name='زمان مطالعه (دقیقه)')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('published', 'منتشر شده'), ('archived', 'بایگانی شده')], default='draft', max_length=15, verbose_name='وضعیت')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('related_products', models.ManyToManyField(blank=True, to='core.product', verbose_name='محصولات مرتبط')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='blog.articlecategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان آموزش')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('youtube_embed_url', models.URLField(help_text='لینک مستقیم iframe', verbose_name='لینک Embed یوتیوب/آپارات')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='tutorials/thumbnails/', verbose_name='تصویر کاور ویدیو')),
                ('attachment_file', models.FileField(blank=True, help_text='فایل لایه باز یا قالب برای دانلود کاربر', null=True, upload_to='tutorials/attachments/', verbose_name='فایل تمرین/قالب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/نمایش داده شود؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('related_products', models.ManyToManyField(blank=True, to='core.product', verbose_name='مربوط به کدام محصولات؟')),
            ],
            options={
                'verbose_name': 'آموزش',
                'verbose_name_plural': 'آموزش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
