# Generated by Django 5.2.9 on 2025-12-25 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method', models.CharField(choices=[('terminal', 'باربری ترمینال'), ('pickup', 'تحویل حضوری(درب کارگاه)'), ('other', 'سایر')], default='other', max_length=50, verbose_name='روش ارسال')),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری پستی')),
                ('driver_info', models.TextField(blank=True, help_text='نام و شماره تماس پیک', verbose_name='اطلاعات راننده/پیک')),
                ('shipping_cost_real', models.DecimalField(decimal_places=0, default=0, help_text='هزینه\u200cای که ما به پست پرداختیم', max_digits=15, verbose_name='هزینه واقعی ارسال')),
                ('status', models.CharField(choices=[('processing', 'در حال پردازش انبار'), ('ready_to_ship', 'آماده ارسال'), ('dispatched', 'تحویل به متصدی'), ('delivered', 'تحویل مشتری شد'), ('returned', 'مرجوع شد')], default='processing', max_length=20, verbose_name='وضعیت مرسوله')),
                ('expected_delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='زمان احتمالی تحویل')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خروج از انبار')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل به مشتری')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.address', verbose_name='آدرس مقصد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='core.order', verbose_name='سفارش مربوطه')),
            ],
            options={
                'verbose_name': 'مرسوله پستی',
                'verbose_name_plural': 'مرسولات پستی',
                'db_table': 'admin_order_shipments',
            },
        ),
        migrations.CreateModel(
            name='OrderPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_uuid', models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='شناسه لیبل')),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام مشتری')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('order_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='تصویر سفارش')),
                ('content_summary', models.TextField(blank=True, help_text='مثلا: ۱۰۰۰ عدد کارت ویزیت لمینت', verbose_name='خلاصه محتویات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('packed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='انباردار')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='logistics.ordershipment', verbose_name='مرسوله')),
            ],
            options={
                'verbose_name': 'بسته/کارتن',
                'verbose_name_plural': 'بسته\u200cها و لیبل\u200cها',
                'db_table': 'admin_order_packages',
            },
        ),
    ]
