# مرحله اول: ساخت
FROM node:22-bookworm AS build-stage
WORKDIR /app

# تنظیم registry
RUN npm config set registry https://mirror-npm.runflare.com/

# کپی package files
COPY package.json package-lock.json ./
RUN npm install

# کپی کد منبع
COPY . .

# Build برای production
RUN npm run build

# مرحله دوم: اجرا با Nginx
FROM nginx:stable-alpine

# کپی build شده
COPY --from=build-stage /app/dist /usr/share/nginx/html

# کپی تنظیمات Nginx
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Expose port
EXPOSE 80

# اجرای Nginx
CMD ["nginx", "-g", "daemon off;"]