# مرحله اول: ساخت
FROM node:22-bookworm AS build-stage
WORKDIR /app

RUN npm config set registry https://registry.npmmirror.com/

# فقط package.json رو کپی کن (بذار package-lock نادیده گرفته بشه)
COPY package.json ./

RUN npm install --verbose

COPY . .

RUN npm run build

# مرحله دوم: اجرا با Nginx
FROM nginx:stable-alpine
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]