# ۱. هدایت تمام ترافیک HTTP به HTTPS
server {
    listen 80;
    server_name printoo24.com www.printoo24.com;
    
    return 301 https://$host$request_uri;
}

# ۲. پیکربندی اصلی HTTPS
server {
    listen 443 ssl;
    server_name printoo24.com www.printoo24.com;

    # مسیر گواهینامه‌های Self-Signed که خودمون ساختیم
    ssl_certificate /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;

    # تنظیمات امنیتی SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /usr/share/nginx/html;
    index index.html;

    # --- تنظیمات مدیا و استاتیک ---
    location /media/ {
        alias /app/src/media/;
        expires 30d;
    }

    location /static/ {
        alias /app/src/staticfiles/;
        expires 30d;
    }

    # --- تنظیمات API ---
    location /api/v1/ {
        proxy_pass http://customer_site:9010;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # --- تنظیمات ریکت ---
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}