server {
    listen 80;
    server_name localhost;

    # مسیر فایل‌های بیلد شده فرانت‌ند
    root /usr/share/nginx/html;
    index index.html;

    # 1. سرو کردن فایل‌های Media (بسیار مهم برای نمایش تصاویر محصولات و دسته‌بندی‌ها)
    location /media/ {
        # این آدرس دقیقا باید مطابق با مسیر کانتینر در docker-compose باشد
        alias /app/src/media/;
        access_log off;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }

    # 2. سرو کردن فایل‌های Static بک‌ند (برای استایل‌های پنل ادمین و ...)
    location /static/ {
        alias /app/src/staticfiles/;
        access_log off;
        expires 30d;
    }

    # 3. هدایت درخواست‌های API به کانتینر بک‌ند
    location /api/v1/ {
        proxy_pass http://customer_site:9010;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 4. هدایت پنل ادمین (اگر نیاز داری از طریق Nginx باز شود)
    location /admin/ {
        proxy_pass http://customer_site:9010;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 5. مدیریت مسیرهای فرانت‌ند (React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }
}