# Generated by Django 5.2.8 on 2025-11-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customerprofile_options_product_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='height',
            field=models.FloatField(default=0.0, verbose_name='طول'),
        ),
        migrations.AlterField(
            model_name='size',
            name='width',
            field=models.FloatField(default=0.0, verbose_name='عرض'),
        ),
    ]
