# Generated by Django 5.2.8 on 2025-11-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_fileuploadspec_productfileuploadrequirement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('1', 'سفارش معمولی'), ('2', 'سفارش اختصاصی')], default='2', max_length=150, verbose_name='نوع سفارش'),
        ),
    ]
