# Generated by Django 5.2.8 on 2025-11-21 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_province_remove_customerprofile_address_city_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address_order', to='core.address', verbose_name='آدرس'),
        ),
    ]
