# Generated by Django 5.2.8 on 2025-11-14 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_designfile_orderstatus_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'verbose_name': 'مشتری', 'verbose_name_plural': 'مشتریان'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_modifier_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='یک عدد برای تغییر کلی قیمت. مثال: 15.0 برای افزایش 15 درصدی یا -10.0 برای کاهش 10 درصدی.', max_digits=5, verbose_name='درصد تعدیل قیمت'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_square_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='اگر این محصول ابعاد دلخواه دارد، قیمت هر واحد سطح را وارد کنید. در غیر این صورت خالی بگذارید.', max_digits=10, null=True, verbose_name='قیمت بر واحد سطح (مثلا سانتی\u200cمتر مربع)'),
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='price_impact',
            field=models.DecimalField(decimal_places=2, default=0, help_text='مبلغی که به قیمت پایه اضافه یا از آن کسر می\u200cشود (به تومان).', max_digits=10, verbose_name='تأثیر بر قیمت'),
        ),
        migrations.AddField(
            model_name='productsize',
            name='price_impact',
            field=models.DecimalField(decimal_places=2, default=0, help_text='مبلغی که به قیمت پایه اضافه یا از آن کسر می\u200cشود (به تومان).', max_digits=10, verbose_name='تأثیر بر قیمت'),
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('code', models.CharField(max_length=150, verbose_name='کد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی ها',
            },
        ),
        migrations.CreateModel(
            name='OptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=150, verbose_name='مقدار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_value_option', to='core.option')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_value_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مقدار ویژگی',
                'verbose_name_plural': 'مقدار ویژگی ها',
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_impact', models.DecimalField(decimal_places=2, default=0, help_text='مبلغی که به قیمت پایه اضافه یا از آن کسر می\u200cشود (به تومان).', max_digits=10, verbose_name='تأثیر بر قیمت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_option_option', to='core.option')),
                ('option_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_option_option_value', to='core.optionvalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_option_product', to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_option_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی های محصولات',
            },
        ),
    ]
