# Generated by Django 5.2.8 on 2025-11-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.IntegerField(default=0, verbose_name='ترتیب'),
        ),
    ]
