# Generated by Django 5.2.8 on 2025-11-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_productimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accepts_custom_dimensions',
            field=models.BooleanField(default=False, verbose_name='پذیرش اندازه های سطح'),
        ),
    ]
