# Generated by Django 5.2.8 on 2025-11-16 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_accepts_custom_dimensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: طرح رو، طرح پشت، فایل UV', max_length=100, unique=True, verbose_name='نام مشخصات')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'مشخصات آپلود فایل',
                'verbose_name_plural': 'انواع مشخصات آپلود فایل',
            },
        ),
        migrations.CreateModel(
            name='ProductFileUploadRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True, verbose_name='الزامی بودن')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_upload_requirements', to='core.product', verbose_name='محصول')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_requirements', to='core.fileuploadspec', verbose_name='مشخصات')),
            ],
            options={
                'verbose_name': 'نیازمندی آپلود فایل محصول',
                'verbose_name_plural': 'نیازمندی\u200cهای آپلود فایل محصولات',
                'ordering': ['sort_order'],
                'unique_together': {('product', 'spec')},
            },
        ),
        migrations.CreateModel(
            name='CartItemUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cart_uploads/%Y/%m/%d/', verbose_name='فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='core.cartitem', verbose_name='آیتم سبد خرید')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.productfileuploadrequirement', verbose_name='نیازمندی مربوطه')),
            ],
            options={
                'verbose_name': 'فایل آپلود شده سبد خرید',
                'verbose_name_plural': 'فایل\u200cهای آپلود شده سبد خرید',
            },
        ),
    ]
