# Generated by Django 5.2.8 on 2025-11-26 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.province', verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='city',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
