# Generated by Django 5.2.9 on 2025-12-26 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['-created_at'], 'verbose_name': 'کیف پول', 'verbose_name_plural': 'کیف های پول'},
        ),
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'تراکنش کیف پول', 'verbose_name_plural': 'تراکنش های کیف پول'},
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='decimal',
            new_name='balance',
        ),
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='type',
            new_name='transaction_type',
        ),
        migrations.AlterModelTable(
            name='wallet',
            table='customer_wallets',
        ),
        migrations.AlterModelTable(
            name='wallettransaction',
            table='customer_wallet_transactions',
        ),
    ]
