# Generated by Django 5.2.17 on 2026-08-15 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_wallettransaction_transaction_type'),
        ('core', '0028_expense_description_expense_expense_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['-created_at'], 'verbose_name': 'کیف پول', 'verbose_name_plural': 'کیف پول\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'تراکنش کیف پول', 'verbose_name_plural': 'تراکنش\u200cهای کیف پول'},
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='amount_after',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='wallet',
            name='credit_limit',
            field=models.DecimalField(decimal_places=0, default=0, help_text='حداکثر اعتبار قابل استفاده', max_digits=18, verbose_name='سقف اعتبار'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='is_credit_enabled',
            field=models.BooleanField(default=False, verbose_name='اعتبار فعال است؟'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_invoice_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین تاریخ فاکتور'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین تاریخ پرداخت'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='open_orders_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد سفارشات باز'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_deposits',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مجموع واریزها'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_orders',
            field=models.DecimalField(decimal_places=0, default=0, help_text='مجموع مبلغ سفارشات ثبت شده', max_digits=18, verbose_name='مجموع مبلغ سفارشات'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_orders_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد کل سفارشات'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_withdrawals',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مجموع برداشت\u200cها'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='موجودی بعد از تراکنش'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='balance_before',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='موجودی قبل از تراکنش'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='کاربری که تراکنش را ثبت کرده است', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_wallet_transactions', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='core.invoice', verbose_name='فاکتور مرتبط'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='core.order', verbose_name='سفارش مرتبط'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='core.payment', verbose_name='پرداخت مرتبط'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='transaction_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='کد تراکنش'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.wallet', verbose_name='کیف پول'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, help_text='موجودی قابل استفاده مشتری (واحد: دینار)', max_digits=18, verbose_name='موجودی فعلی'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'واریز'), ('withdrawal', 'برداشت'), ('payment', 'پرداخت سفارش'), ('refund', 'برگشت وجه'), ('adjustment', 'تسویه حساب')], max_length=20, verbose_name='نوع تراکنش'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
