# Generated by Django 5.2.11 on 2026-02-21 17:09

import apps.home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_sliderindex_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='site_media/', validators=[apps.home.models.validate_file_size_5mb, apps.home.models.validate_image_and_gif_extension], verbose_name='فایل رسانه')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
            ],
            options={
                'verbose_name': 'رسانه سایت',
                'verbose_name_plural': 'رسانه\u200cهای سایت',
                'db_table': 'customer_site_media',
                'ordering': ['-created_at'],
            },
        ),
    ]
