# Generated by Django 5.2.11 on 2026-02-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sitemedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemedia',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='لینک'),
        ),
    ]
