# Generated by Django 5.2.11 on 2026-02-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articlecategory_created_at_articlecategory_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/covers/', verbose_name='تصویر کاور'),
        ),
    ]
