version = 5.3.1
archive_dir = /etc/letsencrypt/archive/printoo24.com
cert = /etc/letsencrypt/live/printoo24.com/cert.pem
privkey = /etc/letsencrypt/live/printoo24.com/privkey.pem
chain = /etc/letsencrypt/live/printoo24.com/chain.pem
fullchain = /etc/letsencrypt/live/printoo24.com/fullchain.pem
[renewalparams]
account = 534db333643b0ba72ef7621b0d1da3b9
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
printoo24.com = /var/www/certbot
www.printoo24.com = /var/www/certbot
