# Generated by Django 5.2.9 on 2025-12-25 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ واریزی')),
                ('method', models.CharField(choices=[('card_to_card', 'کارت به کارت'), ('bank_transfer', 'حواله بانکی (پایا/ساتنا)'), ('cash', 'وجه نقد (حضوری)'), ('cheque', 'چک'), ('pos', 'دستگاه کارتخوان (حضوری)')], max_length=20, verbose_name='روش پرداخت')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='financial/receipts/%Y/%m/', verbose_name='تصویر فیش/رسید')),
                ('tracking_code', models.CharField(help_text='شماره پیگیری فیش یا حواله', max_length=100, verbose_name='کد پیگیری/ارجاع')),
                ('payment_date', models.DateTimeField(help_text='زمانی که پول واریز شده (طبق فیش)', verbose_name='زمان واریز')),
                ('dest_account', models.CharField(blank=True, help_text='مثلا: بانک ملت - جاری', max_length=100, null=True, verbose_name='واریز به حساب')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید مالی'), ('confirmed', 'تایید شده'), ('rejected', 'رد شده / مغایرت')], default='pending', max_length=20, verbose_name='وضعیت سند')),
                ('rejection_reason', models.TextField(blank=True, help_text='اگر فیش جعلی است یا مبلغ نمی\u200cخواند', verbose_name='دلیل رد شدن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت در سیستم')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_transactions', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.invoice', verbose_name='فاکتور')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'تراکنش / فیش',
                'verbose_name_plural': 'تراکنش\u200cها و فیش\u200cها',
                'db_table': 'admin_financial_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
