# Generated by Django 5.2.9 on 2025-12-25 15:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دسته')),
                ('slug', models.SlugField(unique=True, verbose_name='کد سیستمی')),
                ('cost_type', models.CharField(choices=[('design', 'طراحی'), ('print', 'چاپ'), ('material', 'مواد اولیه'), ('transport', 'حمل و نقل'), ('packing', 'بسته\u200cبندی'), ('storage', 'برون\u200cسپاری'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نوع هزینه')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'دسته هزینه',
                'verbose_name_plural': 'دسته\u200cهای هزینه',
                'db_table': 'admin_order_cost_categories',
            },
        ),
        migrations.CreateModel(
            name='OrderCostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='مثلا: هزینه کاغذ مصرفی بخش افست', max_length=200, verbose_name='عنوان گزارش')),
                ('department', models.CharField(choices=[('design', 'واحد طراحی'), ('production', 'واحد تولید/چاپ'), ('warehouse', 'انبار'), ('logistics', 'لجستیک و ارسال'), ('outsourcing', 'برون\u200cسپاری'), ('management', 'مدیریت (سربار)')], max_length=20, verbose_name='دپارتمان')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ارسال کننده گزارش')),
            ],
            options={
                'verbose_name': 'گزارش هزینه داخلی',
                'verbose_name_plural': 'گزارشات هزینه داخلی',
                'db_table': 'admin_order_cost_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderCostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان (متفرقه)')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات تکمیلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('catalog_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='order.ordercostcategory', verbose_name='شرح هزینه')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.ordercostreport', verbose_name='گزارش مرتبط')),
            ],
            options={
                'verbose_name': 'قلم هزینه',
                'verbose_name_plural': 'اقلام هزینه',
                'db_table': 'admin_order_cost_items',
            },
        ),
        migrations.CreateModel(
            name='OrderCostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='financial/costs/attachments/%Y/%m/', verbose_name='فایل ضمیمه')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='order.ordercostreport', verbose_name='گزارش هزینه')),
            ],
            options={
                'verbose_name': 'پیوست هزینه',
                'verbose_name_plural': 'پیوست\u200cهای هزینه',
                'db_table': 'admin_order_cost_attachments',
            },
        ),
        migrations.CreateModel(
            name='OrderCostSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False, help_text='اگر تیک بخورد، هیچ گزارشی دیگر قابل اضافه شدن نیست (پایان سال مالی یا تسویه نهایی).', verbose_name='قفل شده؟')),
                ('total_material_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='جمع هزینه مواد')),
                ('total_service_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='جمع هزینه خدمات/چاپ')),
                ('total_shipping_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='جمع هزینه ارسال')),
                ('total_overhead_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='جمع سربار/سایر')),
                ('final_total_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='بهای تمام شده کل')),
                ('revenue_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='مبلغ فروش (فاکتور)')),
                ('net_profit', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='سود/زیان خالص')),
                ('profit_margin_percent', models.FloatField(default=0.0, verbose_name='حاشیه سود (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_sheet', to='core.order', verbose_name='سفارش مرتبط')),
            ],
            options={
                'verbose_name': 'سند بهای تمام شده',
                'verbose_name_plural': 'اسناد بهای تمام شده',
                'db_table': 'admin_order_cost_sheets',
            },
        ),
        migrations.AddField(
            model_name='ordercostreport',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='order.ordercostsheet', verbose_name='سند مادر'),
        ),
        migrations.CreateModel(
            name='OrderPrintReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان گزارش')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات فنی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده (اپراتور)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_reports', to='core.order', verbose_name='سفارش مرتبط')),
            ],
            options={
                'verbose_name': 'گزارش مصرف چاپ',
                'verbose_name_plural': 'گزارشات مصرف چاپ',
                'db_table': 'admin_order_print_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPrintItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_items', to='order.ordercostcategory', verbose_name='نوع مواد اولیه')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.orderprintreport', verbose_name='گزارش مرتبط')),
            ],
            options={
                'verbose_name': 'قلم متریال',
                'verbose_name_plural': 'اقلام متریال',
                'db_table': 'admin_order_print_items',
            },
        ),
        migrations.CreateModel(
            name='OrderPrintAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='orders/print_logs/%Y/%m/', verbose_name='فایل/عکس')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='order.orderprintreport', verbose_name='گزارش چاپ')),
            ],
            options={
                'verbose_name': 'پیوست چاپ',
                'verbose_name_plural': 'پیوست\u200cهای چاپ',
                'db_table': 'admin_order_print_attachments',
            },
        ),
        migrations.CreateModel(
            name='OrderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع فرآیند')),
                ('due_date', models.DateTimeField(verbose_name='تاریخ تحویل نهایی (Deadline)')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل واقعی')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='core.order', verbose_name='سفارش مرتبط')),
            ],
            options={
                'verbose_name': 'زمان\u200cبندی سفارش',
                'verbose_name_plural': 'زمان\u200cبندی\u200cهای سفارش',
                'db_table': 'admin_order_schedules',
                'indexes': [models.Index(fields=['start_date', 'due_date'], name='admin_order_start_d_6e08c0_idx'), models.Index(fields=['completed_at'], name='admin_order_complet_1be155_idx')],
            },
        ),
    ]
