# Generated by Django 5.2.9 on 2026-01-28 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'نوع هزینه سفارش',
                'verbose_name_plural': 'نوع هزینه سفارش',
                'db_table': 'admin_order_cost_type',
            },
        ),
        migrations.RemoveField(
            model_name='orderprintitem',
            name='material_type',
        ),
        migrations.RemoveField(
            model_name='orderprintitem',
            name='report',
        ),
        migrations.RemoveField(
            model_name='orderprintreport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='orderprintreport',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordercostreport',
            name='department',
        ),
        migrations.AddField(
            model_name='ordercostreport',
            name='cost_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.ordercosttype', verbose_name='نوع هزینه'),
        ),
        migrations.DeleteModel(
            name='OrderPrintAttachment',
        ),
        migrations.DeleteModel(
            name='OrderPrintItem',
        ),
        migrations.DeleteModel(
            name='OrderPrintReport',
        ),
    ]
