# Generated by Django 5.2.10 on 2026-01-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_ordercosttype_remove_orderprintitem_material_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercosttype',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='اسلاگ'),
        ),
    ]
