# Generated by Django 5.2.11 on 2026-02-13 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_address_postal_code'),
        ('order', '0003_alter_ordercosttype_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFinancialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان سرفصل')),
                ('slug', models.SlugField(unique=True, verbose_name='کد سیستمی')),
                ('operation_type', models.CharField(choices=[('design', 'واحد طراحی'), ('print', 'واحد چاپ/تولید'), ('material', 'تامین مواد اولیه'), ('logistics', 'لجستیک و ارسال'), ('outsourcing', 'برون\u200cسپاری'), ('overhead', 'سربار/عمومی'), ('sales', 'فروش و خدمات')], default='overhead', max_length=20, verbose_name='گروه عملیاتی')),
                ('nature', models.CharField(choices=[('cost', 'هزینه (Financial) - خروجی پول'), ('revenue', 'درآمد (Revenue) - ورودی پول')], default='cost', help_text='مشخص می\u200cکند این قلم در محاسبات سود و زیان، کسر شود یا اضافه.', max_length=10, verbose_name='ماهیت مالی')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'سرفصل مالی سفارش',
                'verbose_name_plural': 'سرفصل\u200cهای مالی سفارش',
                'db_table': 'admin_order_financial_categories',
            },
        ),
        migrations.CreateModel(
            name='OrderFinancialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'تگ مالی',
                'verbose_name_plural': 'تگ\u200cهای مالی',
                'db_table': 'admin_order_financial_types',
            },
        ),
        migrations.RemoveField(
            model_name='ordercostitem',
            name='catalog_item',
        ),
        migrations.RemoveField(
            model_name='ordercostitem',
            name='report',
        ),
        migrations.RemoveField(
            model_name='ordercostreport',
            name='cost_type',
        ),
        migrations.RemoveField(
            model_name='ordercostreport',
            name='sheet',
        ),
        migrations.RemoveField(
            model_name='ordercostreport',
            name='submitter',
        ),
        migrations.RemoveField(
            model_name='ordercostsheet',
            name='order',
        ),
        migrations.CreateModel(
            name='OrderFinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان گزارش')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات تکمیلی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'گزارش مالی',
                'verbose_name_plural': 'گزارشات مالی',
                'db_table': 'admin_order_financial_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderFinancialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان ریز قلم')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('category', models.ForeignKey(help_text='انتخاب سرفصل تعیین می\u200cکند مبلغ اضافه شود یا کم.', on_delete=django.db.models.deletion.PROTECT, to='order.orderfinancialcategory', verbose_name='سرفصل حساب')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.orderfinancialreport', verbose_name='گزارش مرتبط')),
            ],
            options={
                'verbose_name': 'قلم مالی',
                'verbose_name_plural': 'اقلام مالی',
                'db_table': 'admin_order_financial_items',
            },
        ),
        migrations.CreateModel(
            name='OrderFinancialAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='financial/attachments/%Y/%m/', verbose_name='فایل ضمیمه')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان فایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='order.orderfinancialreport', verbose_name='گزارش مرتبط')),
            ],
            options={
                'verbose_name': 'پیوست مالی',
                'verbose_name_plural': 'پیوست\u200cهای مالی',
                'db_table': 'admin_order_financial_attachments',
            },
        ),
        migrations.CreateModel(
            name='OrderFinancialSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_locked', models.BooleanField(default=False, help_text='پس از بستن حساب\u200cهای سفارش، امکان تغییر وجود ندارد.', verbose_name='قفل حسابرسی')),
                ('total_material_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='هزینه مواد')),
                ('total_production_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='هزینه تولید/چاپ')),
                ('total_service_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='هزینه خدمات/طراحی')),
                ('total_delivery_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='هزینه ارسال')),
                ('total_other_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='سایر هزینه\u200cها')),
                ('final_total_cost', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='جمع کل بهای تمام شده')),
                ('total_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='جمع کل درآمد (فاکتور + اضافات)')),
                ('net_profit', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='سود/زیان خالص')),
                ('profit_margin_percent', models.FloatField(default=0.0, verbose_name='حاشیه سود (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_sheet', to='core.order', verbose_name='سفارش مرتبط')),
            ],
            options={
                'verbose_name': 'سند سود و زیان سفارش',
                'verbose_name_plural': 'اسناد سود و زیان',
                'db_table': 'admin_order_financial_sheets',
            },
        ),
        migrations.AddField(
            model_name='orderfinancialreport',
            name='sheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='order.orderfinancialsheet', verbose_name='سند مادر'),
        ),
        migrations.AddField(
            model_name='orderfinancialreport',
            name='financial_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.orderfinancialtype', verbose_name='تگ مالی'),
        ),
        migrations.DeleteModel(
            name='OrderCostAttachment',
        ),
        migrations.DeleteModel(
            name='OrderCostCategory',
        ),
        migrations.DeleteModel(
            name='OrderCostItem',
        ),
        migrations.DeleteModel(
            name='OrderCostType',
        ),
        migrations.DeleteModel(
            name='OrderCostReport',
        ),
        migrations.DeleteModel(
            name='OrderCostSheet',
        ),
    ]
