# Generated by Django 5.2.11 on 2026-02-13 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderfinancialcategory_orderfinancialtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderfinancialcategory',
            name='nature',
        ),
        migrations.AddField(
            model_name='orderfinancialreport',
            name='nature',
            field=models.CharField(choices=[('cost', 'هزینه (Cost) - خروجی'), ('revenue', 'درآمد (Revenue) - ورودی')], default='cost', help_text='تعیین می\u200cکند اقلام این گزارش به درآمد اضافه شوند یا به هزینه.', max_length=10, verbose_name='ماهیت گزارش'),
        ),
        migrations.AlterField(
            model_name='orderfinancialcategory',
            name='operation_type',
            field=models.CharField(choices=[('design', 'واحد طراحی'), ('print', 'واحد چاپ/تولید'), ('material', 'تامین مواد اولیه'), ('logistics', 'لجستیک و ارسال'), ('outsourcing', 'برون\u200cسپاری'), ('overhead', 'سربار/عمومی'), ('sales', 'فروش و خدمات')], default='overhead', help_text='برای تفکیک گزارش\u200cها در نمودارها (مثلا چقدر خرج چاپ شده)', max_length=20, verbose_name='گروه عملیاتی'),
        ),
        migrations.AlterField(
            model_name='orderfinancialitem',
            name='category',
            field=models.ForeignKey(help_text='گروه عملیاتی (چاپ، طراحی و...) را مشخص می\u200cکند.', on_delete=django.db.models.deletion.PROTECT, to='order.orderfinancialcategory', verbose_name='سرفصل حساب'),
        ),
        migrations.AlterField(
            model_name='orderfinancialsheet',
            name='total_revenue',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='جمع کل درآمد (فروش + اضافات)'),
        ),
    ]
