# Generated by Django 5.2.11 on 2026-02-13 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_orderfinancialcategory_nature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfinancialitem',
            name='category',
            field=models.ForeignKey(blank=True, help_text='گروه عملیاتی (چاپ، طراحی و...) را مشخص می\u200cکند.', null=True, on_delete=django.db.models.deletion.PROTECT, to='order.orderfinancialcategory', verbose_name='سرفصل حساب'),
        ),
    ]
