# Generated by Django 5.2.9 on 2025-12-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decimal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مقدار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف های پول',
                'db_table': 'customer_wallet',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'افزایش'), ('2', 'کاهش'), ('3', 'تایید'), ('4', 'رد'), ('5', 'برگشت'), ('6', 'پرداخت'), ('7', 'دریافت'), ('8', 'تایید پرداخت'), ('9', 'رد پرداخت')], max_length=150, verbose_name='نوع')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مقدار')),
                ('amount_after', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مقدار بعد از عملیات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به روزرسانی')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش های کیف پول',
                'db_table': 'customer_wallet_transaction',
            },
        ),
    ]
