# Generated by Django 5.2.11 on 2026-02-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_wallet_options_alter_wallettransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('1', 'زیادبوون'), ('2', 'کەمبوون'), ('3', 'پشتڕاستکردنەوە'), ('4', 'ڕەتکردنەوە'), ('5', 'گەڕاندنەوە'), ('6', 'پارەدان'), ('7', 'وەرگرتن'), ('8', 'پشتڕاستکردنەوەی پارەدان'), ('9', 'ڕەتکردنەوەی پارەدان')], max_length=150, verbose_name='نوع'),
        ),
    ]
