# Generated by Django 5.2.9 on 2025-12-29 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_category_productcategoryrelation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productquantity',
            name='price',
        ),
    ]
