# Generated by Django 5.2.9 on 2026-01-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_company_name_order_full_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='is_system',
            field=models.BooleanField(default=False, editable=False, verbose_name='سیستمی'),
        ),
        migrations.AddField(
            model_name='orderstatusgroup',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='سیستمی'),
        ),
    ]
