# Generated by Django 5.2.9 on 2026-01-08 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orderstatus_is_system_orderstatusgroup_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_attachment', to='core.product', verbose_name='محصولات'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='نام'),
        ),
        migrations.DeleteModel(
            name='ProductAttachment',
        ),
    ]
