# Generated by Django 5.2.11 on 2026-02-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_attachment_product_alter_attachment_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'فایل پیوست', 'verbose_name_plural': 'فایل های پیوست'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='آدرس ایمیل'),
        ),
    ]
