# Generated by Django 5.2.11 on 2026-02-20 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_orderstatus_options_productquantity_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOptionCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('show', 'نمایش دادن و فعال کردن (Enable)'), ('hide', 'مخفی کردن و غیرفعال کردن (Disable/Exclude)')], default='show', max_length=20, verbose_name='نوع قانون')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('required_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enables_targets', to='core.productoptionvalue', verbose_name='مقدار پیش\u200cنیاز (شرط)')),
                ('target_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_rules', to='core.productoptionvalue', verbose_name='مقدار هدف (وابسته)')),
            ],
            options={
                'verbose_name': 'قانون وابستگی ویژگی',
                'verbose_name_plural': 'قوانین وابستگی ویژگی\u200cها',
                'unique_together': {('target_value', 'required_value')},
            },
        ),
    ]
