# Generated by Django 5.2.11 on 2026-02-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_productoptioncondition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.CharField(blank=True, null=True, verbose_name='سررسید'),
        ),
    ]
