# Generated by Django 5.2.11 on 2026-02-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_invoice_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='قیمت نمایشی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('1', 'داواکاریی ئاسایی'), ('2', 'داواکاریی تایبەت')], default='2', max_length=150, verbose_name='نوع سفارش'),
        ),
    ]
