# Generated by Django 5.2.11 on 2026-02-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_productoption_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfield',
            name='multi_select_operator',
            field=models.CharField(choices=[('add', 'جمع (+)'), ('sub', 'تفریق (-)'), ('mul', 'ضرب (*)'), ('div', 'تقسیم (/)')], default='add', help_text='اگر فیلد چندانتخابی است، مقادیرِ تیک\u200cخورده با چه عملگری با هم محاسبه شوند؟', max_length=10, verbose_name='عملگر داخلی چندانتخابی'),
        ),
    ]
