# Generated by Django 5.2.11 on 2026-02-23 21:49

from django.db import migrations, models
import random
import string

def migrate_phone_numbers(apps, schema_editor):
    """
    این تابع داده‌های واقعی را از پروفایل به یوزر منتقل می‌کند
    و اگر کاربری (مثل ادمین) پروفایل نداشت، به او یک شماره رندوم یکتا می‌دهد.
    """
    User = apps.get_model('core', 'User')
    CustomerProfile = apps.get_model('core', 'CustomerProfile')
    
    for user in User.objects.all():
        random_digits = "".join(random.choices(string.digits, k=9))
        user.phone_number = f"09{random_digits}"
            
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_productfield_multi_select_operator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        
        # ۱. اضافه کردن فیلد به صورت موقت (بدون یونیک و با قابلیت خالی بودن)
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, blank=True, verbose_name='شماره تماس'),
        ),
        
        # ۲. اجرای اسکریپت پایتونی برای پر کردن شماره تلفن‌ها به صورت ایمن
        migrations.RunPython(
            code=migrate_phone_numbers,
            reverse_code=migrations.RunPython.noop # برای قابلیت برگشت‌پذیری مایگریشن
        ),
        
        # ۳. سفت و سخت کردن فیلد (الزامی و یکتا)
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='شماره تماس'),
        ),
        
        # ۴. حالا که دیتا با موفقیت منتقل شد، فیلدهای اضافی را حذف می‌کنیم
        migrations.RemoveField(
            model_name='customerprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]