# Generated by Django 5.2.11 on 2026-02-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_productfieldchoice_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='عدد کوچکتر = نمایش در رتبه بالاتر (مثال: 1 بالاتر از 2 است)', verbose_name='ترتیب نمایش'),
        ),
    ]
