# Generated by Django 5.2.11 on 2026-03-22 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_productcategory_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldChoiceDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان مقدار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
        ),
        migrations.CreateModel(
            name='FieldDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='عنوان فیلد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات پیش\u200cفرض')),
                ('field_type', models.CharField(choices=[('text', 'متن کوتاه'), ('textarea', 'متن چندخطی'), ('number', 'عدد'), ('single_select', 'تک انتخابی (Radio)'), ('multi_select', 'چند انتخابی (Checkbox)'), ('dropdown', 'کشویی (Select)')], default='dropdown', max_length=20, verbose_name='نوع فیلد')),
                ('multi_select_operator', models.CharField(choices=[('add', 'جمع (+)'), ('sub', 'تفریق (-)'), ('mul', 'ضرب (*)'), ('div', 'تقسیم (/)')], default='add', max_length=10, verbose_name='عملگر داخلی چندانتخابی')),
                ('is_quantity_field', models.BooleanField(default=False, verbose_name='آیا این فیلد همان تیراژ است؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
        ),
        migrations.RenameField(
            model_name='productfieldchoice',
            old_name='field',
            new_name='product_field',
        ),
        migrations.AlterField(
            model_name='productfield',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال بودن در این محصول'),
        ),
        migrations.AlterField(
            model_name='productfield',
            name='is_required',
            field=models.BooleanField(default=False, verbose_name='اجباری بودن برای این محصول'),
        ),
        migrations.AlterField(
            model_name='productfield',
            name='numeric_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='مقدار عددی پایه (برای فرمول این محصول)'),
        ),
        migrations.AlterField(
            model_name='productfieldchoice',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='گزینه پیش\u200cفرض'),
        ),
        migrations.AlterField(
            model_name='productfieldchoice',
            name='numeric_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14, verbose_name='مقدار عددی (ارزش این گزینه در این محصول)'),
        ),
        migrations.AddField(
            model_name='productfieldchoice',
            name='choice_dict',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.fieldchoicedictionary', verbose_name='مقدار مرجع'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='productfieldchoice',
            unique_together={('product_field', 'choice_dict')},
        ),
        migrations.AddField(
            model_name='fieldchoicedictionary',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='core.fielddictionary', verbose_name='فیلد پدر'),
        ),
        migrations.AddField(
            model_name='productfield',
            name='field_dict',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='core.fielddictionary', verbose_name='فیلد مرجع'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='productfield',
            unique_together={('product', 'field_dict')},
        ),
        migrations.RemoveField(
            model_name='productfieldchoice',
            name='title',
        ),
        migrations.AlterUniqueTogether(
            name='fieldchoicedictionary',
            unique_together={('field', 'title')},
        ),
        migrations.RemoveField(
            model_name='productfield',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productfield',
            name='field_type',
        ),
        migrations.RemoveField(
            model_name='productfield',
            name='is_quantity_field',
        ),
        migrations.RemoveField(
            model_name='productfield',
            name='multi_select_operator',
        ),
        migrations.RemoveField(
            model_name='productfield',
            name='title',
        ),
    ]
