# Generated by Django 5.2.14 on 2026-06-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_product_slug_alter_productcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='postal_code',
        ),
    ]
