# Generated by Django 5.2.14 on 2026-06-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_product_price_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=12, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='show_price',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=14, verbose_name='قیمت نمایشی'),
        )
    ]
