# Generated by Django 5.2.14 on 2026-07-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_product_price_alter_product_show_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategoryrelation',
            options={'ordering': ['-is_primary', 'priority', 'order'], 'verbose_name': 'رابطه محصول-دسته', 'verbose_name_plural': 'روابط محصول-دسته'},
        ),
        migrations.AddField(
            model_name='productcategoryrelation',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='آیا این دسته\u200cبندی، دسته اصلی محصول است؟ (حداکثر یک عدد)'),
        ),
        migrations.AddField(
            model_name='productcategoryrelation',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='ترتیب نمایش در بین دسته\u200cبندی\u200cهای همان محصول'),
        ),
        migrations.AddField(
            model_name='productcategoryrelation',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'بسیار مهم'), (2, 'مهم'), (3, 'معمولی'), (4, 'فرعی')], default=3, help_text='سطح اهمیت این دسته\u200cبندی برای محصول'),
        ),
        migrations.AddConstraint(
            model_name='productcategoryrelation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='unique_primary_category_per_product'),
        ),
    ]
