# Generated by Django 5.2.17 on 2026-08-15 10:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_productcategoryrelation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='کد هزینه'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='تاریخ هزینه'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('printing', 'هزینه چاپ'), ('material', 'هزینه متریال'), ('design', 'هزینه طراحی'), ('cutting', 'هزینه برش'), ('installation', 'هزینه نصب'), ('shipping', 'هزینه حمل'), ('packaging', 'هزینه بسته\u200cبندی'), ('labor', 'هزینه نیروی کار'), ('supplier', 'خرید از تأمین\u200cکننده'), ('urgent', 'هزینه فوری'), ('rework', 'هزینه اصلاح یا دوباره\u200cکاری'), ('other', 'سایر هزینه\u200cها')], default='other', max_length=20, verbose_name='نوع هزینه'),
        ),
        migrations.AddField(
            model_name='expense',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد'),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='expenses/receipts/%Y/%m/%d/', verbose_name='فایل رسید'),
        ),
        migrations.AddField(
            model_name='expense',
            name='registered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registered_expenses', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده'),
        ),
        migrations.AddField(
            model_name='expense',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='قیمت واحد'),
        ),
        migrations.AddField(
            model_name='order',
            name='deposit_paid',
            field=models.DecimalField(decimal_places=0, default=0, help_text='مبلغ پیش\u200cپرداخت پرداخت شده', max_digits=18, verbose_name='پیش\u200cپرداخت انجام شده'),
        ),
        migrations.AddField(
            model_name='order',
            name='deposit_required',
            field=models.DecimalField(decimal_places=0, default=0, help_text='حداقل مبلغ پیش\u200cپرداخت مورد نیاز', max_digits=18, verbose_name='حداقل پیش\u200cپرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='مبلغ تخفیف اعمال شده روی سفارش', max_digits=18, verbose_name='مبلغ تخفیف'),
        ),
        migrations.AddField(
            model_name='order',
            name='final_price',
            field=models.DecimalField(decimal_places=0, default=0, help_text='قیمت نهایی پس از اعمال تخفیف، مالیات و هزینه ارسال', max_digits=18, verbose_name='قیمت نهایی'),
        ),
        migrations.AddField(
            model_name='order',
            name='financial_status',
            field=models.CharField(choices=[('no_payment', 'بدون پرداخت'), ('awaiting_deposit', 'در انتظار پیش\u200cپرداخت'), ('deposit_paid', 'پیش\u200cپرداخت شده'), ('fully_paid', 'پرداخت کامل'), ('has_balance', 'دارای مانده حساب'), ('settled', 'تسویه شده'), ('cancelled', 'لغو شده'), ('refunded', 'برگشت خورده'), ('debtor', 'بدهکار'), ('creditor', 'بستانکار')], db_index=True, default='no_payment', max_length=20, verbose_name='وضعیت مالی'),
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ صدور فاکتور'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='مجموع مبالغ پرداخت شده برای این سفارش', max_digits=18, verbose_name='مبلغ پرداخت شده'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, help_text='آخرین مهلت برای پرداخت', null=True, verbose_name='مهلت پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='مبلغ باقی مانده برای تسویه کامل', max_digits=18, verbose_name='مانده حساب'),
        ),
        migrations.AddField(
            model_name='order',
            name='settlement_date',
            field=models.DateTimeField(blank=True, help_text='تاریخ تسویه کامل سفارش', null=True, verbose_name='تاریخ تسویه'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='هزینه ارسال'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, help_text='مجموع قیمت اقلام قبل از اعمال تخفیف', max_digits=18, verbose_name='جمع کل (قبل از تخفیف)'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='مبلغ مالیات (در صورت نیاز)', max_digits=18, verbose_name='مالیات'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='شماره پرداخت')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='مبلغ پرداخت')),
                ('method', models.CharField(choices=[('online', 'پرداخت آنلاین'), ('cash', 'نقدی'), ('bank_transfer', 'حواله بانکی'), ('card_to_card', 'کارت به کارت'), ('office', 'پرداخت در دفتر'), ('whatsapp', 'پرداخت از طریق واتساپ'), ('manual', 'ثبت دستی')], max_length=20, verbose_name='روش پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('reference_number', models.CharField(blank=True, help_text='شماره تراکنش بانکی، شماره حواله، یا کد پیگیری', max_length=100, null=True, verbose_name='شماره مرجع')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='payments/receipts/%Y/%m/%d/', verbose_name='رسید / تصویر پرداخت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پرداخت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_payments', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.invoice', verbose_name='فاکتور مرتبط')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.order', verbose_name='سفارش مرتبط')),
                ('registered_by', models.ForeignKey(blank=True, help_text='ادمینی که پرداخت را ثبت کرده (برای پرداخت\u200cهای دستی)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registered_payments', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده پرداخت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='پرداخت کننده')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-payment_date'],
            },
        ),
    ]
