# Generated by Django 5.2.17 on 2026-08-15 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_expense_description_expense_expense_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('online', 'پرداخت آنلاین'), ('cash', 'نقدی'), ('bank_transfer', 'حواله بانکی'), ('card_to_card', 'کارت به کارت'), ('office', 'پرداخت در دفتر'), ('whatsapp', 'پرداخت از طریق واتساپ'), ('manual', 'ثبت دستی'), ('wallet', 'کیف پول')], max_length=20, verbose_name='روش پرداخت'),
        ),
        migrations.CreateModel(
            name='FinancialLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('quotation_created', 'ایجاد پیش\u200cفاکتور'), ('price_updated', 'اصلاح قیمت'), ('order_created', 'ثبت سفارش'), ('payment_received', 'دریافت پرداخت'), ('payment_approved', 'تایید پرداخت'), ('payment_rejected', 'رد پرداخت'), ('invoice_created', 'صدور فاکتور'), ('invoice_updated', 'اصلاح فاکتور'), ('expense_added', 'افزودن هزینه'), ('wallet_deposit', 'واریز به کیف پول'), ('wallet_withdrawal', 'برداشت از کیف پول'), ('refund_processed', 'برگشت وجه'), ('order_settled', 'تسویه سفارش'), ('order_cancelled', 'لغو سفارش')], db_index=True, max_length=30, verbose_name='نوع عملیات')),
                ('field_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام فیلد')),
                ('old_value', models.JSONField(blank=True, null=True, verbose_name='مقدار قبلی')),
                ('new_value', models.JSONField(blank=True, null=True, verbose_name='مقدار جدید')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='دلیل تغییر')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='مرورگر')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_financial_logs', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_logs', to='core.invoice', verbose_name='فاکتور مرتبط')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_logs', to='core.order', verbose_name='سفارش')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_logs', to='core.payment', verbose_name='پرداخت مرتبط')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر مرتبط')),
            ],
            options={
                'verbose_name': 'لاگ مالی',
                'verbose_name_plural': 'لاگ\u200cهای مالی',
                'db_table': 'core_financial_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
