# Generated by Django 5.2.17 on 2026-08-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_quotation_cart_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financiallog',
            name='action_type',
            field=models.CharField(choices=[('quotation_created', 'ایجاد پیش\u200cفاکتور'), ('quotation_approved', 'تأیید پیش\u200cفاکتور توسط مشتری'), ('price_updated', 'اصلاح قیمت'), ('order_created', 'ثبت سفارش'), ('payment_received', 'دریافت پرداخت'), ('payment_approved', 'تایید پرداخت'), ('payment_rejected', 'رد پرداخت'), ('invoice_created', 'صدور فاکتور'), ('invoice_updated', 'اصلاح فاکتور'), ('expense_added', 'افزودن هزینه'), ('wallet_deposit', 'واریز به کیف پول'), ('wallet_withdrawal', 'برداشت از کیف پول'), ('refund_processed', 'برگشت وجه'), ('order_settled', 'تسویه سفارش'), ('order_cancelled', 'لغو سفارش')], db_index=True, max_length=30, verbose_name='نوع عملیات'),
        ),
    ]
